//! Reflective STATEFUL-REDUCER capability surface (UNWALL-1-STATEFUL-NL).
//!
//! Makes the engine's per-tick `(state: i64, arr: [i64]) -> i64` reducer synthesis
//! (`solver::search_families::search_stateful_reducer`) NL-reachable by reflecting
//! its op surface into mineable capability descriptors — the SAME pattern
//! `array_transform::mineable_array_ops` / `mineable_element_map_ops` use for the
//! array families.
//!
//! WHY THIS IS EMERGENT, NOT A HAND TABLE:
//!   * The op SET each descriptor names is a `(reducer, op)` pair drawn FROM the
//!     engine's own enumeration slices — `solver::STATEFUL_REDUCER_NAMES` and
//!     `solver::STATEFUL_REDUCER_OPS` (the exact `g` and `op` in `state op g(arr)`
//!     that `search_stateful_reducer` searches). `stateful_ops_exhaustive` asserts
//!     every descriptor's `(reducer, op)` is present in those engine slices, so a
//!     descriptor cannot name a stateful update the engine cannot synthesize +
//!     verify; if the engine surface shrinks, the guard fails closed.
//!   * Each descriptor's `example_cases` are AUTO-GENERATED by RUNNING the engine's
//!     OWN reference (`solver::stateful_reducer_apply`, the SAME `state op g(arr)`
//!     `search_stateful_reducer` verifies against) on canonical `(state, arr)`
//!     probes — never hand-written. So the mined rows ARE the engine's semantics,
//!     and a request resolved to one of these lemmas synthesizes the REAL
//!     `search_stateful_reducer` program against those rows.
//!
//! The descriptor carries a `(state, arr) -> i64` runner so the capability miner
//! can manufacture two-input `[{Int}, {Array}]` example rows; `infer_signature`
//! then derives `(a: i64, b: [i64]) -> i64`, and `search_stateful_reducer`'s
//! signature gate (`[I64, ArrayI64]`) fires — routing the request to the stateful
//! synthesis rather than a plain array reduce.

/// A mined stateful per-tick reducer capability: `f(state, arr) = state op g(arr)`
/// for a `(reducer, op)` pair drawn from the engine's stateful surface.
pub struct MinedStatefulOp {
    /// Canonical lemma for the NL capability registry.
    pub lemma: &'static str,
    /// The engine reducer name `g` (must be in `solver::STATEFUL_REDUCER_NAMES`).
    pub reducer: &'static str,
    /// The engine state-combine op (must be in `solver::STATEFUL_REDUCER_OPS`).
    pub op: &'static str,
    /// Run the engine's OWN reference update on a canonical `(state, arr)`,
    /// manufacturing example rows. Returns `None` if the engine surface no longer
    /// supports this `(reducer, op)` (fail-closed against drift).
    pub run: fn(i64, &[i64]) -> Option<i64>,
}

/// The named stateful update kinds exposed to NL. Each variant binds a human
/// lemma to a `(reducer, op)` pair the engine's `search_stateful_reducer` already
/// enumerates. The exhaustive `match` in `kind_descriptor` keeps this enum the
/// single source; the `stateful_ops_exhaustive` guard binds every variant's
/// `(reducer, op)` to the engine slices.
#[derive(Clone, Copy, PartialEq, Eq)]
enum StatefulReducerKind {
    /// `state + sum(arr)` — a running total that accumulates each tick's array.
    RunningTotal,
    /// `state - sum(arr)` — a running balance that draws each tick's array down.
    RunningDeduction,
    /// `state.max(max(arr))` — a high-water mark across ticks.
    RunningMax,
    /// `state.min(min(arr))` — a low-water mark across ticks.
    RunningMin,
    /// `state + count_positive(arr)` — accumulate the count of positive events.
    RunningPositiveCount,
}

impl StatefulReducerKind {
    /// All named kinds, in a stable order (drives the mined emission order).
    const ALL: [StatefulReducerKind; 5] = [
        StatefulReducerKind::RunningTotal,
        StatefulReducerKind::RunningDeduction,
        StatefulReducerKind::RunningMax,
        StatefulReducerKind::RunningMin,
        StatefulReducerKind::RunningPositiveCount,
    ];

    /// Canonical lemma + the engine `(reducer, op)` it binds to. EXHAUSTIVE over
    /// the enum: a new variant forces a new arm here.
    fn descriptor(self) -> (&'static str, &'static str, &'static str) {
        // (lemma, reducer, op)
        match self {
            StatefulReducerKind::RunningTotal => ("running_total", "sum", "+"),
            StatefulReducerKind::RunningDeduction => ("running_deduction", "sum", "-"),
            StatefulReducerKind::RunningMax => ("running_max", "max", "max"),
            StatefulReducerKind::RunningMin => ("running_min", "min", "min"),
            StatefulReducerKind::RunningPositiveCount => {
                ("running_positive_count", "count_positive", "+")
            }
        }
    }
}

/// Enumerate the synthesizable stateful per-tick reducers by reflecting
/// `StatefulReducerKind`. Lemma + behaviour come from the enum and the engine's
/// OWN `stateful_reducer_apply` reference, not a hand table.
pub fn mineable_stateful_ops() -> Vec<MinedStatefulOp> {
    fn run_running_total(state: i64, arr: &[i64]) -> Option<i64> {
        crate::solver::stateful_reducer_apply("sum", "+", state, arr)
    }
    fn run_running_deduction(state: i64, arr: &[i64]) -> Option<i64> {
        crate::solver::stateful_reducer_apply("sum", "-", state, arr)
    }
    fn run_running_max(state: i64, arr: &[i64]) -> Option<i64> {
        crate::solver::stateful_reducer_apply("max", "max", state, arr)
    }
    fn run_running_min(state: i64, arr: &[i64]) -> Option<i64> {
        crate::solver::stateful_reducer_apply("min", "min", state, arr)
    }
    fn run_running_positive_count(state: i64, arr: &[i64]) -> Option<i64> {
        crate::solver::stateful_reducer_apply("count_positive", "+", state, arr)
    }
    let run_for = |k: StatefulReducerKind| -> fn(i64, &[i64]) -> Option<i64> {
        match k {
            StatefulReducerKind::RunningTotal => run_running_total,
            StatefulReducerKind::RunningDeduction => run_running_deduction,
            StatefulReducerKind::RunningMax => run_running_max,
            StatefulReducerKind::RunningMin => run_running_min,
            StatefulReducerKind::RunningPositiveCount => run_running_positive_count,
        }
    };
    StatefulReducerKind::ALL
        .iter()
        .map(|&k| {
            let (lemma, reducer, op) = k.descriptor();
            MinedStatefulOp {
                lemma,
                reducer,
                op,
                run: run_for(k),
            }
        })
        .collect()
}

/// EMERGENCE GUARD (test-enforced): assert the mined stateful op set is bound to
/// the engine surface — every descriptor's `(reducer, op)` is present in the
/// engine's `STATEFUL_REDUCER_NAMES` / `STATEFUL_REDUCER_OPS` slices that
/// `search_stateful_reducer` enumerates. The exhaustive `match` in
/// `descriptor` fails to compile if a NEW `StatefulReducerKind` variant is added
/// without a decision; this runtime check proves the vocabulary is DERIVED from
/// the engine surface, not hand-typed, and that each mined row the miner produces
/// IS the engine's own reference output.
#[cfg(test)]
pub(crate) fn stateful_ops_exhaustive() {
    use crate::solver::{STATEFUL_REDUCER_NAMES, STATEFUL_REDUCER_OPS};
    for op in mineable_stateful_ops() {
        assert!(
            STATEFUL_REDUCER_NAMES.contains(&op.reducer),
            "stateful lemma {} names reducer {:?} absent from engine surface {:?}",
            op.lemma,
            op.reducer,
            STATEFUL_REDUCER_NAMES
        );
        assert!(
            STATEFUL_REDUCER_OPS.contains(&op.op),
            "stateful lemma {} names op {:?} absent from engine surface {:?}",
            op.lemma,
            op.op,
            STATEFUL_REDUCER_OPS
        );
        // The runner must equal the engine's own reference for this pair.
        let probe: &[i64] = &[3, -1, 2];
        assert_eq!(
            (op.run)(5, probe),
            crate::solver::stateful_reducer_apply(op.reducer, op.op, 5, probe),
            "stateful lemma {} runner diverged from engine reference",
            op.lemma
        );
    }
    // Every enum variant is emitted (no missing).
    assert_eq!(
        mineable_stateful_ops().len(),
        StatefulReducerKind::ALL.len(),
        "mined stateful surface drifted from StatefulReducerKind enum"
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn surface_is_bound_to_engine() {
        stateful_ops_exhaustive();
    }

    /// The running examples ARE the engine's per-tick state evolution: applying
    /// the runner twice (feeding the prior result back as `state`) accumulates,
    /// proving real per-tick state (not a stateless array reduce).
    #[test]
    fn running_total_evolves_state_per_tick() {
        let total = mineable_stateful_ops()
            .into_iter()
            .find(|o| o.lemma == "running_total")
            .unwrap();
        let s0 = 0;
        let s1 = (total.run)(s0, &[1, 2, 3]).unwrap(); // 0 + 6 = 6
        let s2 = (total.run)(s1, &[10, 20]).unwrap(); // 6 + 30 = 36
        assert_eq!(s1, 6);
        assert_eq!(s2, 36);
    }
}
