// Auto-generated by nCPU LOOP-3D generated backend (BackendIR).
// Rules: 2 synthesized handler(s)
// Description: score a learned game rule: ten points per catch plus a five point bonus | convert hit points lost into a signed penalty score: twice the loss minus three
// Store: file
// Compile:
//   memory: rustc --edition=2021 generated_rule_backend.rs -o generated_rule_backend
//   file:   rustc --edition=2021 generated_rule_backend.rs -o generated_rule_backend
//   sqlite: rustc --edition=2021 generated_rule_backend.rs -o generated_rule_backend -l sqlite3

use std::io::{self, BufRead, BufReader, Read, Write};
use std::net::{TcpListener, TcpStream};
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use std::thread;

#[derive(Clone, Debug, PartialEq, Eq)]
struct Event {
    rule: String,
    input: i64,
    output: i64,
}

trait EventStore: Send + Sync {
    fn append(&self, event: Event) -> io::Result<()>;
    fn list(&self) -> io::Result<Vec<Event>>;
}

struct FileStore {
    path: PathBuf,
    events: Mutex<Vec<Event>>,
}

impl FileStore {
    fn open(path: PathBuf) -> io::Result<Self> {
        let mut events = Vec::new();
        if path.exists() {
            let file = std::fs::File::open(&path)?;
            let reader = BufReader::new(file);
            for line in reader.lines() {
                let line = line?;
                if line.trim().is_empty() {
                    continue;
                }
                if let Some(event) = parse_event_line(&line) {
                    events.push(event);
                }
            }
        }
        Ok(Self {
            path,
            events: Mutex::new(events),
        })
    }

    fn persist_line(path: &PathBuf, event: &Event) -> io::Result<()> {
        use std::fs::OpenOptions;
        let mut file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(path)?;
        writeln!(file, "{{\"rule\":\"{}\",\"input\":{},\"output\":{}}}", event.rule, event.input, event.output)?;
        file.sync_all()?;
        Ok(())
    }
}

impl EventStore for FileStore {
    fn append(&self, event: Event) -> io::Result<()> {
        Self::persist_line(&self.path, &event)?;
        self.events
            .lock()
            .map_err(|_| io::Error::new(io::ErrorKind::Other, "store lock poisoned"))?
            .push(event);
        Ok(())
    }

    fn list(&self) -> io::Result<Vec<Event>> {
        Ok(self
            .events
            .lock()
            .map_err(|_| io::Error::new(io::ErrorKind::Other, "store lock poisoned"))?
            .clone())
    }
}

fn parse_event_line(line: &str) -> Option<Event> {
    let rule = extract_json_string(line, "rule")?;
    let input = extract_json_i64(line, "input")?;
    let output = extract_json_i64(line, "output")?;
    Some(Event { rule, input, output })
}

fn extract_json_string(body: &str, field: &str) -> Option<String> {
    let key = format!("\"{}\"", field);
    let idx = body.find(&key)?;
    let after_key = &body[idx + key.len()..];
    let colon = after_key.find(':')?;
    let mut s = after_key[colon + 1..].trim_start();
    if !s.starts_with('"') {
        return None;
    }
    s = &s[1..];
    let end = s.find('"')?;
    Some(s[..end].to_string())
}

fn extract_json_i64(body: &str, field: &str) -> Option<i64> {
    let key = format!("\"{}\"", field);
    let idx = body.find(&key)?;
    let after_key = &body[idx + key.len()..];
    let colon = after_key.find(':')?;
    let mut s = after_key[colon + 1..].trim_start();
    let mut end = 0usize;
    for (i, ch) in s.char_indices() {
        if i == 0 && ch == '-' {
            end = ch.len_utf8();
            continue;
        }
        if ch.is_ascii_digit() {
            end = i + ch.len_utf8();
        } else {
            break;
        }
    }
    if end == 0 {
        return None;
    }
    s = &s[..end];
    s.parse().ok()
}


fn score_bonus(x: i64) -> i64 {
    return ((10 * x) + 5);
}


fn damage_penalty(x: i64) -> i64 {
    return ((2 * x) + -3);
}


fn main() {
    let args: Vec<String> = std::env::args().collect();
    let port = arg_value(&args, "--port").unwrap_or_else(|| "7800".to_string());
    let host = arg_value(&args, "--host").unwrap_or_else(|| "127.0.0.1".to_string());
    let bind = format!("{}:{}", host, port);
    let listener = TcpListener::bind(&bind).unwrap_or_else(|e| {
        eprintln!("cannot bind {bind}: {e}");
        std::process::exit(1);
    });
    let addr = listener.local_addr().expect("local addr");
        let store_path = arg_value(&args, "--store-path")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("backend_events.jsonl"));
    let store: Arc<dyn EventStore> = Arc::new(
        FileStore::open(store_path).unwrap_or_else(|e| {
            eprintln!("cannot open file store: {e}");
            std::process::exit(1);
        }),
    );
    println!("BACKEND_READY http://{}", addr);
    std::io::stdout().flush().ok();

    for stream in listener.incoming() {
        match stream {
            Ok(stream) => {
                let store = Arc::clone(&store);
                thread::spawn(move || {
                    let _ = handle_connection(stream, store);
                });
            }
            Err(e) => eprintln!("accept error: {e}"),
        }
    }
}

fn arg_value(args: &[String], flag: &str) -> Option<String> {
    args.windows(2).find(|w| w[0] == flag).map(|w| w[1].clone())
}

fn handle_connection(mut stream: TcpStream, store: Arc<dyn EventStore>) -> io::Result<()> {
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut request_line = String::new();
    if reader.read_line(&mut request_line)? == 0 {
        return Ok(());
    }
    let mut parts = request_line.split_whitespace();
    let method = parts.next().unwrap_or("").to_string();
    let path = parts.next().unwrap_or("").to_string();
    let mut content_length = 0usize;
    loop {
        let mut line = String::new();
        let n = reader.read_line(&mut line)?;
        if n == 0 || line == "\r\n" || line == "\n" {
            break;
        }
        if let Some((k, v)) = line.split_once(':') {
            if k.trim().eq_ignore_ascii_case("content-length") {
                content_length = v.trim().parse().unwrap_or(0);
            }
        }
    }
    let mut body = vec![0u8; content_length];
    if content_length > 0 {
        reader.read_exact(&mut body)?;
    }
    let body = String::from_utf8_lossy(&body);

    match (method.as_str(), path.as_str()) {
        ("GET", "/health") => write_response(
            &mut stream,
            200,
            &format!(
                "{{\"ok\":true,\"service\":\"generated-rule-backend\",\"store\":\"file\",\"rules\":2}}"
            ),
        ),
        ("GET", "/rules") => write_response(&mut stream, 200, "{\"rules\":[{\"name\":\"score_bonus\",\"method\":\"search_polynomial_multi\"},{\"name\":\"damage_penalty\",\"method\":\"search_polynomial_multi\"}]}"),
        ("GET", "/events") => {
            let snapshot = store.list().unwrap_or_default();
            write_response(&mut stream, 200, &events_json(&snapshot))
        }
        ("POST", "/rules/score_bonus/evaluate") => match extract_i64_field(&body, "input") {
            Some(input) => {
                let output = score_bonus(input);
                let event = Event {
                    rule: "score_bonus".to_string(),
                    input,
                    output,
                };
                if let Err(err) = store.append(event) {
                    return write_response(
                        &mut stream,
                        500,
                        &format!("{{\"error\":\"store append failed: {}\"}}", err),
                    );
                }
                write_response(
                    &mut stream,
                    200,
                    &format!(
                        "{{\"rule\":\"score_bonus\",\"input\":{},\"output\":{}}}",
                        input, output
                    ),
                )
            }
            None => write_response(
                &mut stream,
                400,
                "{\"error\":\"expected JSON body with integer field input\"}",
            ),
        },
        ("POST", "/rules/damage_penalty/evaluate") => match extract_i64_field(&body, "input") {
            Some(input) => {
                let output = damage_penalty(input);
                let event = Event {
                    rule: "damage_penalty".to_string(),
                    input,
                    output,
                };
                if let Err(err) = store.append(event) {
                    return write_response(
                        &mut stream,
                        500,
                        &format!("{{\"error\":\"store append failed: {}\"}}", err),
                    );
                }
                write_response(
                    &mut stream,
                    200,
                    &format!(
                        "{{\"rule\":\"damage_penalty\",\"input\":{},\"output\":{}}}",
                        input, output
                    ),
                )
            }
            None => write_response(
                &mut stream,
                400,
                "{\"error\":\"expected JSON body with integer field input\"}",
            ),
        },
        _ => write_response(&mut stream, 404, "{\"error\":\"unknown route\"}"),
    }
}

fn extract_i64_field(body: &str, field: &str) -> Option<i64> {
    let key = format!("\"{}\"", field);
    let idx = body.find(&key)?;
    let after_key = &body[idx + key.len()..];
    let colon = after_key.find(':')?;
    let mut s = after_key[colon + 1..].trim_start();
    let mut end = 0usize;
    for (i, ch) in s.char_indices() {
        if i == 0 && ch == '-' {
            end = ch.len_utf8();
            continue;
        }
        if ch.is_ascii_digit() {
            end = i + ch.len_utf8();
        } else {
            break;
        }
    }
    if end == 0 {
        return None;
    }
    s = &s[..end];
    s.parse().ok()
}

fn events_json(events: &[Event]) -> String {
    let rows = events
        .iter()
        .map(|e| format!(
            "{{\"rule\":\"{}\",\"input\":{},\"output\":{}}}",
            e.rule, e.input, e.output
        ))
        .collect::<Vec<_>>()
        .join(",");
    format!("{{\"events\":[{}],\"count\":{}}}", rows, events.len())
}

fn write_response(stream: &mut TcpStream, status: u16, body: &str) -> io::Result<()> {
    let status_text = match status {
        200 => "OK",
        400 => "Bad Request",
        404 => "Not Found",
        500 => "Internal Server Error",
        _ => "Server Error",
    };
    let response = format!(
        "HTTP/1.1 {} {}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        status,
        status_text,
        body.len(),
        body
    );
    stream.write_all(response.as_bytes())?;
    stream.flush()
}
