// Auto-generated by nCPU LOOP-3B generated backend MVP.
// Business rule: score a learned game rule: ten points per catch plus a five point bonus
// Synthesis method: search_polynomial_multi
// Compile directly: rustc --edition=2021 generated_rule_backend.rs -o generated_rule_backend

use std::io::{BufRead, BufReader, Read, Write};
use std::net::{TcpListener, TcpStream};
use std::sync::{Arc, Mutex};
use std::thread;

#[derive(Clone, Debug)]
struct Event {
    input: i64,
    output: i64,
}

fn score_bonus(x: i64) -> i64 {
    return ((10 * x) + 5);
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let port = arg_value(&args, "--port").unwrap_or_else(|| "7800".to_string());
    let host = arg_value(&args, "--host").unwrap_or_else(|| "127.0.0.1".to_string());
    let bind = format!("{}:{}", host, port);
    let listener = TcpListener::bind(&bind).unwrap_or_else(|e| {
        eprintln!("cannot bind {bind}: {e}");
        std::process::exit(1);
    });
    let addr = listener.local_addr().expect("local addr");
    println!("BACKEND_READY http://{}", addr);
    std::io::stdout().flush().ok();

    let events = Arc::new(Mutex::new(Vec::<Event>::new()));
    for stream in listener.incoming() {
        match stream {
            Ok(stream) => {
                let events = Arc::clone(&events);
                thread::spawn(move || {
                    let _ = handle_connection(stream, events);
                });
            }
            Err(e) => eprintln!("accept error: {e}"),
        }
    }
}

fn arg_value(args: &[String], flag: &str) -> Option<String> {
    args.windows(2).find(|w| w[0] == flag).map(|w| w[1].clone())
}

fn handle_connection(mut stream: TcpStream, events: Arc<Mutex<Vec<Event>>>) -> std::io::Result<()> {
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut request_line = String::new();
    if reader.read_line(&mut request_line)? == 0 {
        return Ok(());
    }
    let mut parts = request_line.split_whitespace();
    let method = parts.next().unwrap_or("").to_string();
    let path = parts.next().unwrap_or("").to_string();
    let mut content_length = 0usize;
    loop {
        let mut line = String::new();
        let n = reader.read_line(&mut line)?;
        if n == 0 || line == "\r\n" || line == "\n" {
            break;
        }
        if let Some((k, v)) = line.split_once(':') {
            if k.trim().eq_ignore_ascii_case("content-length") {
                content_length = v.trim().parse().unwrap_or(0);
            }
        }
    }
    let mut body = vec![0u8; content_length];
    if content_length > 0 {
        reader.read_exact(&mut body)?;
    }
    let body = String::from_utf8_lossy(&body);

    match (method.as_str(), path.as_str()) {
        ("GET", "/health") => write_response(&mut stream, 200, "{\"ok\":true,\"service\":\"generated-rule-backend\"}"),
        ("GET", "/rules") => write_response(&mut stream, 200, "{\"rules\":[{\"name\":\"score_bonus\",\"method\":\"search_polynomial_multi\"}]}"),
        ("GET", "/events") => {
            let snapshot = events.lock().map(|ev| ev.clone()).unwrap_or_default();
            write_response(&mut stream, 200, &events_json(&snapshot))
        }
        ("POST", "/rules/score_bonus/evaluate") => match extract_i64_field(&body, "input") {
            Some(input) => {
                let output = score_bonus(input);
                if let Ok(mut ev) = events.lock() {
                    ev.push(Event { input, output });
                }
                write_response(&mut stream, 200, &format!("{{\"rule\":\"score_bonus\",\"input\":{},\"output\":{}}}", input, output))
            }
            None => write_response(&mut stream, 400, "{\"error\":\"expected JSON body with integer field input\"}"),
        },
        _ => write_response(&mut stream, 404, "{\"error\":\"unknown route\"}"),
    }
}

fn extract_i64_field(body: &str, field: &str) -> Option<i64> {
    let key = format!("\"{}\"", field);
    let idx = body.find(&key)?;
    let after_key = &body[idx + key.len()..];
    let colon = after_key.find(':')?;
    let mut s = after_key[colon + 1..].trim_start();
    let mut end = 0usize;
    for (i, ch) in s.char_indices() {
        if i == 0 && ch == '-' {
            end = ch.len_utf8();
            continue;
        }
        if ch.is_ascii_digit() {
            end = i + ch.len_utf8();
        } else {
            break;
        }
    }
    if end == 0 {
        return None;
    }
    s = &s[..end];
    s.parse().ok()
}

fn events_json(events: &[Event]) -> String {
    let rows = events
        .iter()
        .map(|e| format!("{{\"input\":{},\"output\":{}}}", e.input, e.output))
        .collect::<Vec<_>>()
        .join(",");
    format!("{{\"events\":[{}],\"count\":{}}}", rows, events.len())
}

fn write_response(stream: &mut TcpStream, status: u16, body: &str) -> std::io::Result<()> {
    let status_text = match status {
        200 => "OK",
        400 => "Bad Request",
        404 => "Not Found",
        _ => "Server Error",
    };
    let response = format!(
        "HTTP/1.1 {} {}\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
        status,
        status_text,
        body.len(),
        body
    );
    stream.write_all(response.as_bytes())?;
    stream.flush()
}
