"""
Minimal training script for the JEPA Machine World Model.

This demonstrates the core loop:
1. Load traces generated by generate_machine_traces.py
2. Train the predictor to forecast next latent state
3. (Future) Use proper JEPA objectives + uncertainty

Run after generating traces:
    python -m ncpu.world_model.train_je_world_model --data machine_traces.pt --epochs 20
"""

import argparse
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader

from ncpu.world_model.je_world_model import JEWorldModel, JEWMConfig


def train_epoch(model: JEWorldModel, loader: DataLoader, optimizer: torch.optim.Optimizer, device: str):
    model.train()
    total_loss = 0.0

    for batch in loader:
        s_before, action, s_after = [x.to(device) for x in batch]

        optimizer.zero_grad()
        out = model.forward_for_training(s_before, action, s_after)
        loss = out["loss"]
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=str, required=True, help="Path to traces .pt file")
    parser.add_argument("--epochs", type=int, default=15)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--device", type=str, default="cpu")
    parser.add_argument("--save", type=str, default="jewm_checkpoint.pt")
    args = parser.parse_args()

    device = args.device
    if device == "cuda" and not torch.cuda.is_available():
        device = "cpu"
    if device == "mps" and not torch.backends.mps.is_available():
        device = "cpu"

    print(f"Loading traces from {args.data}...")
    data = torch.load(args.data, map_location="cpu")

    states_before = data["states_before"].float()
    actions = data["actions"].float()
    states_after = data["states_after"].float()

    dataset = TensorDataset(states_before, actions, states_after)
    loader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True, drop_last=True)

    print(f"Training on {len(dataset)} transitions | device={device}")

    config = JEWMConfig(
        state_dim=states_before.shape[1],
        action_dim=actions.shape[1],
        hidden_dim=128,
        num_predictor_layers=3,
    )
    model = JEWorldModel(config).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    for epoch in range(1, args.epochs + 1):
        loss = train_epoch(model, loader, optimizer, device)
        print(f"Epoch {epoch:02d} | loss = {loss:.6f}")

    Path(args.save).parent.mkdir(parents=True, exist_ok=True)
    torch.save({
        "model_state": model.state_dict(),
        "config": config.to_dict(),
    }, args.save)
    print(f"\nSaved checkpoint to {args.save}")


if __name__ == "__main__":
    main()