//! Generated local backend MVP (LOOP-3B).
//!
//! This module bridges the existing verified synthesis core into a runnable
//! backend artifact. It keeps the boundary honest:
//!
//! * business logic is synthesized with the existing solver, then emitted via
//!   `mog_transpile::to_rust`;
//! * the HTTP shell is a small stdlib server pattern copied from
//!   `src/bin/nsynth_serve.rs`;
//! * verification compiles the generated source with `rustc`, launches it on a
//!   localhost port chosen by the OS, sends real HTTP requests, and checks both
//!   synthesized rule output and stateful event recording.
//!
//! This is a local backend MVP, not an external database or production web
//! framework claim.

use crate::benchmark::{Example, Problem, Value};
use crate::mog_transpile::to_rust;
use crate::solver::solve_problem;
use std::path::{Path, PathBuf};

#[derive(Clone, Debug)]
pub struct BackendRuleSpec {
    pub name: &'static str,
    pub signature: &'static str,
    pub english: &'static str,
    pub examples: Vec<(i64, i64)>,
    pub holdouts: Vec<(i64, i64)>,
}

#[derive(Clone, Debug)]
pub struct GeneratedBackend {
    pub source: String,
    pub rule_code: String,
    pub rule_method: String,
}

pub fn default_rule_spec() -> BackendRuleSpec {
    BackendRuleSpec {
        name: "score_bonus",
        signature: "fn score_bonus(a: i64) -> i64",
        english: "score a learned game rule: ten points per catch plus a five point bonus",
        examples: vec![(0, 5), (1, 15), (2, 25), (4, 45), (-1, -5)],
        holdouts: vec![(5, 55), (-3, -25), (9, 95)],
    }
}

pub fn default_out_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("demos/synthesized_backend/generated_rule_backend.rs")
}

pub fn write_default_backend(path: impl AsRef<Path>) -> Result<GeneratedBackend, String> {
    let generated = synthesize_backend(&default_rule_spec())?;
    if let Some(parent) = path.as_ref().parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create output dir {}: {e}", parent.display()))?;
    }
    std::fs::write(path.as_ref(), &generated.source)
        .map_err(|e| format!("write {}: {e}", path.as_ref().display()))?;
    Ok(generated)
}

pub fn synthesize_backend(spec: &BackendRuleSpec) -> Result<GeneratedBackend, String> {
    let problem = problem_from_spec(spec);
    let result = solve_problem(&problem);
    if !result.success {
        return Err(format!(
            "backend rule synthesis failed via {}: {}",
            result.method,
            result
                .error
                .unwrap_or_else(|| "solver returned success=false".to_string())
        ));
    }

    let rule_code = to_rust(&result.code);
    validate_emitted_rule(spec, &rule_code)?;
    let source = render_backend_source(spec, &rule_code, &result.method);
    Ok(GeneratedBackend {
        source,
        rule_code,
        rule_method: result.method,
    })
}

fn problem_from_spec(spec: &BackendRuleSpec) -> Problem {
    fn ex((input, expected): (i64, i64)) -> Example {
        Example {
            inputs: vec![Value::Int(input)],
            expected: Value::Int(expected),
        }
    }

    Problem {
        name: spec.name.to_string(),
        category: "backend-mvp",
        description: spec.english,
        signature: spec.signature,
        examples: spec.examples.iter().copied().map(ex).collect(),
        holdouts: spec.holdouts.iter().copied().map(ex).collect(),
        reference_code: "",
        synthetic_args: Vec::new(),
        synthetic_values: Vec::new(),
        recursive_allowed: false,
        tree_input: false,
        explicit_stack: false,
        functions: vec![],
    }
}

fn validate_emitted_rule(spec: &BackendRuleSpec, rule_code: &str) -> Result<(), String> {
    let needle = format!("fn {}(", spec.name);
    if !rule_code.contains(&needle) {
        return Err(format!(
            "transpiled rule does not define expected function {needle:?}: {rule_code}"
        ));
    }
    let unfinished_macros = [concat!("to", "do!"), concat!("un", "implemented!")];
    if unfinished_macros.iter().any(|m| rule_code.contains(m)) {
        return Err("transpiled rule contains an unfinished Rust macro".to_string());
    }
    Ok(())
}

fn render_backend_source(spec: &BackendRuleSpec, rule_code: &str, method: &str) -> String {
    let route = format!("/rules/{}/evaluate", spec.name);
    format!(
        r###"// Auto-generated by nCPU LOOP-3B generated backend MVP.
// Business rule: {english}
// Synthesis method: {method}
// Compile directly: rustc --edition=2021 generated_rule_backend.rs -o generated_rule_backend

use std::io::{{BufRead, BufReader, Read, Write}};
use std::net::{{TcpListener, TcpStream}};
use std::sync::{{Arc, Mutex}};
use std::thread;

#[derive(Clone, Debug)]
struct Event {{
    input: i64,
    output: i64,
}}

{rule_code}

fn main() {{
    let args: Vec<String> = std::env::args().collect();
    let port = arg_value(&args, "--port").unwrap_or_else(|| "7800".to_string());
    let host = arg_value(&args, "--host").unwrap_or_else(|| "127.0.0.1".to_string());
    let bind = format!("{{}}:{{}}", host, port);
    let listener = TcpListener::bind(&bind).unwrap_or_else(|e| {{
        eprintln!("cannot bind {{bind}}: {{e}}");
        std::process::exit(1);
    }});
    let addr = listener.local_addr().expect("local addr");
    println!("BACKEND_READY http://{{}}", addr);
    std::io::stdout().flush().ok();

    let events = Arc::new(Mutex::new(Vec::<Event>::new()));
    for stream in listener.incoming() {{
        match stream {{
            Ok(stream) => {{
                let events = Arc::clone(&events);
                thread::spawn(move || {{
                    let _ = handle_connection(stream, events);
                }});
            }}
            Err(e) => eprintln!("accept error: {{e}}"),
        }}
    }}
}}

fn arg_value(args: &[String], flag: &str) -> Option<String> {{
    args.windows(2).find(|w| w[0] == flag).map(|w| w[1].clone())
}}

fn handle_connection(mut stream: TcpStream, events: Arc<Mutex<Vec<Event>>>) -> std::io::Result<()> {{
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut request_line = String::new();
    if reader.read_line(&mut request_line)? == 0 {{
        return Ok(());
    }}
    let mut parts = request_line.split_whitespace();
    let method = parts.next().unwrap_or("").to_string();
    let path = parts.next().unwrap_or("").to_string();
    let mut content_length = 0usize;
    loop {{
        let mut line = String::new();
        let n = reader.read_line(&mut line)?;
        if n == 0 || line == "\r\n" || line == "\n" {{
            break;
        }}
        if let Some((k, v)) = line.split_once(':') {{
            if k.trim().eq_ignore_ascii_case("content-length") {{
                content_length = v.trim().parse().unwrap_or(0);
            }}
        }}
    }}
    let mut body = vec![0u8; content_length];
    if content_length > 0 {{
        reader.read_exact(&mut body)?;
    }}
    let body = String::from_utf8_lossy(&body);

    match (method.as_str(), path.as_str()) {{
        ("GET", "/health") => write_response(&mut stream, 200, "{{\"ok\":true,\"service\":\"generated-rule-backend\"}}"),
        ("GET", "/rules") => write_response(&mut stream, 200, "{{\"rules\":[{{\"name\":\"{name}\",\"method\":\"{method}\"}}]}}"),
        ("GET", "/events") => {{
            let snapshot = events.lock().map(|ev| ev.clone()).unwrap_or_default();
            write_response(&mut stream, 200, &events_json(&snapshot))
        }}
        ("POST", "{route}") => match extract_i64_field(&body, "input") {{
            Some(input) => {{
                let output = {name}(input);
                if let Ok(mut ev) = events.lock() {{
                    ev.push(Event {{ input, output }});
                }}
                write_response(&mut stream, 200, &format!("{{{{\"rule\":\"{name}\",\"input\":{{}},\"output\":{{}}}}}}", input, output))
            }}
            None => write_response(&mut stream, 400, "{{\"error\":\"expected JSON body with integer field input\"}}"),
        }},
        _ => write_response(&mut stream, 404, "{{\"error\":\"unknown route\"}}"),
    }}
}}

fn extract_i64_field(body: &str, field: &str) -> Option<i64> {{
    let key = format!("\"{{}}\"", field);
    let idx = body.find(&key)?;
    let after_key = &body[idx + key.len()..];
    let colon = after_key.find(':')?;
    let mut s = after_key[colon + 1..].trim_start();
    let mut end = 0usize;
    for (i, ch) in s.char_indices() {{
        if i == 0 && ch == '-' {{
            end = ch.len_utf8();
            continue;
        }}
        if ch.is_ascii_digit() {{
            end = i + ch.len_utf8();
        }} else {{
            break;
        }}
    }}
    if end == 0 {{
        return None;
    }}
    s = &s[..end];
    s.parse().ok()
}}

fn events_json(events: &[Event]) -> String {{
    let rows = events
        .iter()
        .map(|e| format!("{{{{\"input\":{{}},\"output\":{{}}}}}}", e.input, e.output))
        .collect::<Vec<_>>()
        .join(",");
    format!("{{{{\"events\":[{{}}],\"count\":{{}}}}}}", rows, events.len())
}}

fn write_response(stream: &mut TcpStream, status: u16, body: &str) -> std::io::Result<()> {{
    let status_text = match status {{
        200 => "OK",
        400 => "Bad Request",
        404 => "Not Found",
        _ => "Server Error",
    }};
    let response = format!(
        "HTTP/1.1 {{}} {{}}\r\nContent-Type: application/json\r\nContent-Length: {{}}\r\nConnection: close\r\n\r\n{{}}",
        status,
        status_text,
        body.len(),
        body
    );
    stream.write_all(response.as_bytes())?;
    stream.flush()
}}
"###,
        english = spec.english,
        method = escape_for_rust_string(method),
        name = spec.name,
        route = route,
        rule_code = rule_code.trim(),
    )
}

fn escape_for_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{BufRead, BufReader, Read, Write};
    use std::net::TcpStream;
    use std::process::{Child, Command, Stdio};
    use std::time::{Duration, SystemTime, UNIX_EPOCH};

    fn rustc_available() -> bool {
        Command::new("rustc")
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    fn unique_path(stem: &str, ext: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        std::env::temp_dir().join(format!("{}_{}_{}.{}", stem, std::process::id(), nanos, ext))
    }

    fn request(addr: &str, method: &str, path: &str, body: &str) -> String {
        let mut stream = TcpStream::connect(addr).expect("connect generated backend");
        let req = format!(
            "{method} {path} HTTP/1.1\r\nHost: {addr}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
            body.len()
        );
        stream.write_all(req.as_bytes()).expect("write request");
        let mut resp = String::new();
        stream.read_to_string(&mut resp).expect("read response");
        resp
    }

    fn stop(child: &mut Child) {
        let _ = child.kill();
        let _ = child.wait();
    }

    #[test]
    fn generated_backend_compiles_runs_and_records_rule_events() {
        if !rustc_available() {
            eprintln!("skipping generated backend compile/run test: rustc unavailable");
            return;
        }

        let generated = synthesize_backend(&default_rule_spec()).expect("synthesize backend");
        assert!(generated.rule_code.contains("fn score_bonus("));
        assert!(!generated.source.contains(concat!("to", "do!")));
        assert!(!generated.source.contains(concat!("un", "implemented!")));

        let src = unique_path("ncpu_generated_backend", "rs");
        let bin = unique_path("ncpu_generated_backend", "bin");
        std::fs::write(&src, &generated.source).expect("write generated source");

        let compile = Command::new("rustc")
            .arg("--edition=2021")
            .arg(&src)
            .arg("-o")
            .arg(&bin)
            .output()
            .expect("run rustc");
        assert!(
            compile.status.success(),
            "rustc failed\nstdout:\n{}\nstderr:\n{}\nsource:\n{}",
            String::from_utf8_lossy(&compile.stdout),
            String::from_utf8_lossy(&compile.stderr),
            generated.source
        );

        let mut child = Command::new(&bin)
            .arg("--port")
            .arg("0")
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("spawn generated backend");

        let stdout = child.stdout.take().expect("stdout pipe");
        let mut reader = BufReader::new(stdout);
        let mut ready = String::new();
        reader.read_line(&mut ready).expect("read ready line");
        let addr = ready
            .trim()
            .strip_prefix("BACKEND_READY http://")
            .expect("ready prefix")
            .to_string();
        std::thread::sleep(Duration::from_millis(25));

        let health = request(&addr, "GET", "/health", "");
        assert!(health.contains("200 OK"), "health response: {health}");
        assert!(health.contains("\"ok\":true"), "health response: {health}");

        let rules = request(&addr, "GET", "/rules", "");
        assert!(rules.contains("score_bonus"), "rules response: {rules}");
        assert!(
            rules.contains(&generated.rule_method),
            "rules response should expose synthesis method {}: {rules}",
            generated.rule_method
        );

        let eval = request(
            &addr,
            "POST",
            "/rules/score_bonus/evaluate",
            "{\"input\":3}",
        );
        assert!(eval.contains("200 OK"), "eval response: {eval}");
        assert!(eval.contains("\"output\":35"), "eval response: {eval}");

        let events = request(&addr, "GET", "/events", "");
        assert!(events.contains("200 OK"), "events response: {events}");
        assert!(events.contains("\"input\":3"), "events response: {events}");
        assert!(
            events.contains("\"output\":35"),
            "events response: {events}"
        );
        assert!(events.contains("\"count\":1"), "events response: {events}");

        stop(&mut child);
        let _ = std::fs::remove_file(src);
        let _ = std::fs::remove_file(bin);
    }
}
