//! Capability AUTO-MINER (NL-BRIDGE-2-AUTO-MINER).
//!
//! Reflects the engine's OWN synthesizable operator surface into capability
//! Entity records (the JSON the NL bridge loads through the existing
//! `coding_registry.json` seam), so the NL vocabulary becomes EMERGENT and
//! self-growing instead of a hand-typed phrase->op table.
//!
//! WHY THIS IS EMERGENT, NOT A HAND LIST:
//!   * The op SET is reflected from the engine symbol tables —
//!     `string_synth::mineable_string_ops()` (derived from the `SExpr` enum) and
//!     `synthesis::array_transform::mineable_array_ops()` (derived from the
//!     `ReorderKind` enum). Add an operator variant to either enum + re-run the
//!     miner and the capability appears with NO hand edit; the exhaustive `match`
//!     guards in those modules fail closed if a new variant is left unclassified.
//!   * Each op's `example_cases` are AUTO-GENERATED by RUNNING the op's REAL
//!     evaluator (`eval_s` / the order-op semantics) on canonical inputs — the
//!     same "run the code to manufacture teacher examples" trick used by
//!     `teacher_examples_from_code` (differentiable.rs:249). No expected output
//!     is hand-written.
//!   * Only PURE + DETERMINISTIC + auto-verifiable ops are emitted. Side-effecting
//!     / non-deterministic / unimplemented ops are NEVER mined (see
//!     `assert_no_impure_ops_mined` in the tests), so the fail-closed NL gate is
//!     never handed a capability the engine cannot synthesize + verify.
//!
//! The miner is an OFFLINE build step (run via the `mine_capabilities` bin or a
//! test) that produces a COMMITTED JSON file in the SAME schema as
//! `coding_registry.json`; the runtime stays pure-Rust and merely loads it via
//! the existing `Registry::from_json` path. Re-running the miner is byte-stable.

use serde_json::{json, Value};

/// Canonical input strings the string ops are exercised on to manufacture
/// example_cases. Every probe carries BOTH surrounding whitespace AND mixed case
/// AND length > 1, so that EVERY mined op (`trim`, `lowercase`, `uppercase`,
/// `reverse_string`) produces a NON-identity, mutually-distinct output on the
/// whole set — otherwise a faster specialist (e.g. the suffix-conditioned
/// `morph_transduce`) can overfit a degenerate rule on the identity-heavy rows.
/// The set yields >=3 DISTINCT (input,output) rows for every op so the bridge's
/// fresh-holdout differential check always has a held-out probe.
const STRING_PROBES: &[&str] = &[
    " Hello ",
    "World ",
    " AbC",
    "MiXeD ",
    " nSynth ",
    "  Xy  ",
];

/// Canonical input arrays the array order ops are exercised on.
const ARRAY_PROBES: &[&[i64]] = &[&[3, 1, 2], &[5, 4, 6, 4], &[1], &[2, 2, 1, 3]];

/// Canonical `(state, arr)` probes the STATEFUL per-tick reducers are exercised
/// on to manufacture two-input example rows. Each carries BOTH a non-trivial seed
/// state AND an array mixing positive/negative/zero so the rows DISCRIMINATE the
/// intended `(reducer, op)` from the others in the engine surface (e.g. `running_
/// total` vs `running_max` give different outputs on these), and so each op yields
/// >=3 DISTINCT (state, arr) -> result rows for the bridge's fresh-holdout check.
const STATEFUL_PROBES: &[(i64, &[i64])] = &[
    (0, &[1, 2, 3]),
    (10, &[5, -2, 0]),
    (-5, &[2, 9, 1]),
    (100, &[-1, 0, -4]),
];

/// Canonical input arrays the elementwise maps are exercised on. Includes BOTH
/// negative AND positive values so EVERY mined map (negate / double / increment /
/// square / abs) produces a NON-identity, mutually-distinct output — in particular
/// `abs` must see a negative to be a real transform, and the rows stay >=3 distinct
/// for every op so the bridge's fresh-holdout differential check has a held-out probe.
const ELEMENT_MAP_PROBES: &[&[i64]] =
    &[&[-3, 1, -2], &[5, -4, 6, -4], &[-1], &[2, -2, 1, -3]];

/// Hand-authored NL surface FORMS (synonyms + a one-line gloss) per mined lemma.
/// These are presentation metadata for the comprehension layer — NOT the op set
/// or its behaviour (both of which are reflected + auto-run). The lemma keys are
/// asserted to be EXACTLY the reflected engine surface in the tests, so this map
/// cannot smuggle in an op the engine does not actually expose.
fn nl_surface(lemma: &str) -> (Vec<&'static str>, &'static str, &'static str) {
    // (synonyms, definition, domain)
    match lemma {
        "uppercase" => (
            vec!["uppercased", "upcase", "capitalize_all"],
            "Convert every character of a string to upper case",
            "string",
        ),
        "lowercase" => (
            vec!["lowercased", "downcase"],
            "Convert every character of a string to lower case",
            "string",
        ),
        "trim" => (
            vec!["strip", "trimmed"],
            "Remove leading and trailing whitespace from a string",
            "string",
        ),
        "reverse_string" => (
            vec!["reversed_string"],
            "Reverse the characters of a string",
            "string",
        ),
        "sort" => (
            vec!["sorted", "order"],
            "Sort array in ascending order",
            "array",
        ),
        "reverse" => (
            vec!["reversed"],
            "Reverse order of array elements",
            "array",
        ),
        // ── NL-BRIDGE-3A: fixed elementwise array maps (Vec<i64> -> Vec<i64>) ──
        "double_each" => (
            vec!["double_all", "double_values", "twice_each"],
            "Multiply every element of an array by two",
            "array",
        ),
        "negate_each" => (
            vec!["negate_all", "negate_values"],
            "Negate every element of an array",
            "array",
        ),
        "increment_each" => (
            vec!["increment_all", "add_one_each", "bump_each"],
            "Add one to every element of an array",
            "array",
        ),
        "square_each" => (
            vec!["square_all", "square_values"],
            "Square every element of an array",
            "array",
        ),
        "abs_each" => (
            vec!["abs_all", "absolute_each"],
            "Take the absolute value of every element of an array",
            "array",
        ),
        // ── UNWALL-1-STATEFUL-NL: per-tick (state, arr) -> state reducers ──
        "running_total" => (
            vec!["running_sum", "accumulate", "accumulator", "running_accumulator"],
            "Update a running total by adding the sum of this tick's array to the state",
            "stateful",
        ),
        "running_deduction" => (
            vec!["running_balance", "drain", "deplete"],
            "Update a running balance by subtracting the sum of this tick's array from the state",
            "stateful",
        ),
        "running_max" => (
            vec!["high_water_mark", "running_maximum", "peak"],
            "Update a high-water mark with the maximum of this tick's array",
            "stateful",
        ),
        "running_min" => (
            vec!["low_water_mark", "running_minimum", "trough"],
            "Update a low-water mark with the minimum of this tick's array",
            "stateful",
        ),
        "running_positive_count" => (
            vec!["accumulate_positive", "tally_positive", "count_positive_running"],
            "Accumulate the count of positive values seen each tick into the state",
            "stateful",
        ),
        _ => (vec![], "", "unknown"),
    }
}

/// Build the `example_cases` JSON string for a string op by RUNNING its real
/// evaluator on the canonical probes. De-dups by (input,output) so the rows are
/// distinct, and skips inputs the op cannot evaluate (never happens for the
/// total string ops, but kept honest).
fn string_example_cases(run: fn(&str) -> Option<String>) -> Option<String> {
    let mut cases: Vec<Value> = Vec::new();
    let mut seen: std::collections::HashSet<(String, String)> = std::collections::HashSet::new();
    for &probe in STRING_PROBES {
        let out = run(probe)?; // auto-run the REAL op
        if seen.insert((probe.to_string(), out.clone())) {
            cases.push(json!({
                "inputs": [{"type": "Str", "value": probe}],
                "expected": {"type": "Str", "value": out},
            }));
        }
    }
    if cases.len() < 3 {
        return None; // too thin to be a sound, holdout-protected capability
    }
    Some(Value::Array(cases).to_string())
}

/// Build the `example_cases` JSON string for an array order op by RUNNING its real
/// semantics on the canonical probe arrays.
fn array_example_cases(run: fn(&[i64]) -> Vec<i64>) -> Option<String> {
    array_example_cases_on(run, ARRAY_PROBES)
}

/// As `array_example_cases` but over an explicit probe set (used by the
/// elementwise-map family, which needs negatives so `abs` is a real transform).
fn array_example_cases_on(run: fn(&[i64]) -> Vec<i64>, probes: &[&[i64]]) -> Option<String> {
    let mut cases: Vec<Value> = Vec::new();
    let mut seen: std::collections::HashSet<(Vec<i64>, Vec<i64>)> = std::collections::HashSet::new();
    for &probe in probes {
        let out = run(probe); // auto-run the REAL op
        if seen.insert((probe.to_vec(), out.clone())) {
            cases.push(json!({
                "inputs": [{"type": "Array", "value": probe}],
                "expected": {"type": "Array", "value": out},
            }));
        }
    }
    if cases.len() < 3 {
        return None;
    }
    Some(Value::Array(cases).to_string())
}

/// Build the `example_cases` JSON for a STATEFUL per-tick reducer by RUNNING the
/// engine's OWN reference (`solver::stateful_reducer_apply`, surfaced through the
/// descriptor's `run`) on the canonical `(state, arr)` probes. Each row is a
/// two-input `[{Int}, {Array}]` case so the bridge's `infer_signature` derives
/// `(a: i64, b: [i64]) -> i64` and the solver routes to `search_stateful_reducer`.
/// De-dups by (state, arr, out); returns `None` below the >=3 distinct-row floor.
fn stateful_example_cases(run: fn(i64, &[i64]) -> Option<i64>) -> Option<String> {
    let mut cases: Vec<Value> = Vec::new();
    let mut seen: std::collections::HashSet<(i64, Vec<i64>, i64)> = std::collections::HashSet::new();
    for &(state, arr) in STATEFUL_PROBES {
        let out = run(state, arr)?; // auto-run the engine's OWN reference
        if seen.insert((state, arr.to_vec(), out)) {
            cases.push(json!({
                "inputs": [
                    {"type": "Int", "value": state},
                    {"type": "Array", "value": arr},
                ],
                "expected": {"type": "Int", "value": out},
            }));
        }
    }
    if cases.len() < 3 {
        return None; // too thin to be a sound, holdout-protected capability
    }
    Some(Value::Array(cases).to_string())
}

/// One mined STATEFUL reducer capability in the `coding_registry.json` schema.
/// Signature is two-input `(state: i64, arr: [i64]) -> i64`; provenance records
/// the engine `(reducer, op)` the descriptor bound to, proving it came from the
/// engine surface, not a hand table.
fn stateful_entity(
    lemma: &str,
    reducer: &str,
    op: &str,
    example_cases: String,
) -> (String, Value) {
    let (syns, def, domain) = nl_surface(lemma);
    let attrs = json!({
        "arity": "2",
        "input_types": "i64, Vec<i64>",
        "output_type": "i64",
        "nsynth_category": "stateful",
        "default_fn_name": lemma,
        "signature_template": "fn {name}({params}) -> {return}",
        // Provenance: the engine `(reducer, op)` the per-tick update reflects, and
        // that the rows were machine-mined from the engine reference.
        "mined_engine_reducer": reducer,
        "mined_engine_op": op,
        "mined_provenance": "search_families::search_stateful_reducer",
        "example_cases": example_cases,
    });
    let entity = json!({
        "word": lemma,
        "entity_type": "function",
        "definitions": [def],
        "attributes": attrs,
        "relations": {
            "synonym": syns,
            "domain": [domain],
        },
    });
    (lemma.to_string(), entity)
}

/// One mined capability, ready to serialize into the `coding_registry.json`
/// schema (entity = lemma -> {word, entity_type, definitions, attributes,
/// relations}). Built ENTIRELY from reflected engine data + auto-run examples.
fn string_entity(
    lemma: &str,
    code_body: &str,
    example_cases: String,
) -> (String, Value) {
    let (syns, def, domain) = nl_surface(lemma);
    // Derive the default fn-name/category from the engine signature, not by hand:
    // every string op here is arity-1 `string -> string`.
    let attrs = json!({
        "arity": "1",
        "input_types": "string",
        "output_type": "string",
        "nsynth_category": "string",
        // Each string op gets its OWN fn name (like array_entity_with uses `lemma`),
        // so it is addressable by name via synthesize_op_by_name — previously all
        // string ops collided on "transform", making a specific one unselectable.
        "default_fn_name": lemma,
        "signature_template": "fn {name}({params}) -> {return}",
        // Provenance: the engine codegen body this op corresponds to (e.g.
        // `s.lower()`), and that the example_cases were machine-mined.
        "mined_engine_codegen": code_body,
        "mined_provenance": "string_synth::SExpr",
        "example_cases": example_cases,
    });
    let entity = json!({
        "word": lemma,
        "entity_type": "function",
        "definitions": [def],
        "attributes": attrs,
        "relations": {
            "synonym": syns,
            "domain": [domain],
        },
    });
    (lemma.to_string(), entity)
}

fn array_entity_with(lemma: &str, example_cases: String, provenance: &str) -> (String, Value) {
    let (syns, def, domain) = nl_surface(lemma);
    let attrs = json!({
        "arity": "1",
        "input_types": "Vec<i64>",
        "output_type": "Vec<i64>",
        "nsynth_category": "array",
        "default_fn_name": lemma,
        "signature_template": "fn {name}({params}) -> {return}",
        "mined_provenance": provenance,
        "example_cases": example_cases,
    });
    let entity = json!({
        "word": lemma,
        "entity_type": "function",
        "definitions": [def],
        "attributes": attrs,
        "relations": {
            "synonym": syns,
            "domain": [domain],
        },
    });
    (lemma.to_string(), entity)
}

/// Reflect the engine operator surface + auto-run for examples, producing the
/// mined capability registry as a `serde_json::Value` in `coding_registry.json`
/// schema. PURE + DETERMINISTIC: same engine surface -> byte-identical output
/// (entities emitted in a fixed, sorted order; `serde_json::Map` is a BTreeMap so
/// keys are ordered).
/// Split a Rust identifier into lowercase word tokens, handling snake_case,
/// camelCase, and digit boundaries. `"sum_of_digits"` -> `[sum, of, digits]`,
/// `"reverseNumber"` -> `[reverse, number]`, `"decimalToBinary"` ->
/// `[decimal, to, binary]`. Pure identifier morphology — no hand table.
pub(crate) fn tokenize_identifier(name: &str) -> Vec<String> {
    let mut toks: Vec<String> = Vec::new();
    let mut cur = String::new();
    let mut prev: Option<char> = None;
    for c in name.chars() {
        let boundary = c == '_'
            || (c.is_ascii_uppercase() && prev.map(|p| p.is_ascii_lowercase() || p.is_ascii_digit()).unwrap_or(false))
            || (c.is_ascii_digit() && prev.map(|p| p.is_ascii_alphabetic()).unwrap_or(false))
            || (c.is_ascii_alphabetic() && prev.map(|p| p.is_ascii_digit()).unwrap_or(false));
        if c == '_' {
            if !cur.is_empty() {
                toks.push(std::mem::take(&mut cur));
            }
        } else {
            if boundary && !cur.is_empty() {
                toks.push(std::mem::take(&mut cur));
            }
            cur.push(c.to_ascii_lowercase());
        }
        prev = Some(c);
    }
    if !cur.is_empty() {
        toks.push(cur);
    }
    toks
}

/// Derive an NL surface (synonyms, gloss) for an op EMERGENTLY from its name —
/// the identifier's own morphology, no hand-authored phrase table. `sum_of_digits`
/// -> synonyms `["sum of digits", "sum_of_digits"]`, gloss `"Sum of digits"`.
/// Returns None for names too cryptic to ground safely (single-token < 3 chars,
/// or all-tokens-are-noise) so the fail-closed NL gate is never handed a bogus
/// surface that would false-trigger and drop precision.
pub(crate) fn derive_nl_surface(name: &str) -> Option<(Vec<String>, String)> {
    let toks = tokenize_identifier(name);
    if toks.is_empty() {
        return None;
    }
    // Reject un-groundable names: a lone token shorter than 3 chars (`f`, `gcd`
    // is 3 so kept) carries no reliable English signal.
    if toks.len() == 1 && toks[0].len() < 3 {
        return None;
    }
    let phrase = toks.join(" ");
    let mut gloss = phrase.clone();
    if let Some(first) = gloss.get_mut(0..1) {
        first.make_ascii_uppercase();
    }
    let mut syns = vec![phrase];
    if name.contains('_') && name != syns[0] {
        syns.push(name.to_string()); // the raw snake_case identifier as an alias
    }
    Some((syns, gloss))
}

pub fn mine_capabilities() -> Value {
    let mut entities = serde_json::Map::new();

    // ── STRING ops — reflected from string_synth's SExpr enum ────────────────
    let mut string_ops = crate::string_synth::mineable_string_ops();
    // Stable order independent of declaration order.
    string_ops.sort_by(|a, b| a.lemma.cmp(b.lemma));
    for op in string_ops {
        // HONEST: only emit if the op auto-verifies to >=3 distinct example rows.
        if let Some(cases) = string_example_cases(op.run) {
            let (k, v) = string_entity(op.lemma, &op.code_body, cases);
            entities.insert(k, v);
        }
    }

    // ── ARRAY order ops — reflected from array_transform's ReorderKind enum ───
    let mut array_ops = crate::synthesis::array_transform::mineable_array_ops();
    array_ops.sort_by(|a, b| a.lemma.cmp(b.lemma));
    for op in array_ops {
        if let Some(cases) = array_example_cases(op.run) {
            let (k, v) = array_entity_with(op.lemma, cases, "array_transform::ReorderKind");
            entities.insert(k, v);
        }
    }

    // ── ARRAY elementwise maps — reflected from array_transform's ElementMapKind
    //    enum (NL-BRIDGE-3A-MINER-WIDEN). Same Vec<i64> -> Vec<i64> schema as the
    //    order ops; example_cases AUTO-RUN through the real `element_apply`.
    let mut elem_ops = crate::synthesis::array_transform::mineable_element_map_ops();
    elem_ops.sort_by(|a, b| a.lemma.cmp(b.lemma));
    for op in elem_ops {
        if let Some(cases) = array_example_cases_on(op.run, ELEMENT_MAP_PROBES) {
            let (k, v) = array_entity_with(op.lemma, cases, "array_transform::ElementMapKind");
            entities.insert(k, v);
        }
    }

    // ── STATEFUL per-tick reducers — reflected from the engine's
    //    search_stateful_reducer op surface (UNWALL-1-STATEFUL-NL). Two-input
    //    (state, arr) -> state rows AUTO-RUN through the engine's OWN reference
    //    (stateful_reducer_apply), so a request resolved to one of these lemmas
    //    synthesizes the REAL search_stateful_reducer program.
    let mut stateful_ops =
        crate::synthesis::stateful_reducer_surface::mineable_stateful_ops();
    stateful_ops.sort_by(|a, b| a.lemma.cmp(b.lemma));
    for op in stateful_ops {
        if let Some(cases) = stateful_example_cases(op.run) {
            let (k, v) = stateful_entity(op.lemma, op.reducer, op.op, cases);
            entities.insert(k, v);
        }
    }

    json!({
        "_generated": "AUTO-MINED by capability_miner::mine_capabilities — do not edit by hand",
        "entities": Value::Object(entities),
    })
}

/// Serialize the mined registry to a stable, pretty JSON string (newline-
/// terminated). Byte-identical across runs for a fixed engine surface.
pub fn mine_capabilities_json() -> String {
    let mut s = serde_json::to_string_pretty(&mine_capabilities()).expect("serialize mined caps");
    s.push('\n');
    s
}

/// The set of lemmas the miner currently emits (for tests + the
/// remove-now-covered-seeds bookkeeping).
pub fn mined_lemmas() -> Vec<String> {
    let v = mine_capabilities();
    v.get("entities")
        .and_then(|e| e.as_object())
        .map(|m| m.keys().cloned().collect())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tokenize_identifier_handles_snake_camel_digits() {
        assert_eq!(tokenize_identifier("sum_of_digits"), ["sum", "of", "digits"]);
        assert_eq!(tokenize_identifier("reverseNumber"), ["reverse", "number"]);
        assert_eq!(tokenize_identifier("decimalToBinary"), ["decimal", "to", "binary"]);
        assert_eq!(tokenize_identifier("is_prime"), ["is", "prime"]);
        assert_eq!(tokenize_identifier("count_primes_below"), ["count", "primes", "below"]);
    }

    #[test]
    fn derive_nl_surface_grounds_from_name() {
        let (syns, gloss) = derive_nl_surface("sum_of_digits").unwrap();
        assert_eq!(gloss, "Sum of digits");
        assert!(syns.contains(&"sum of digits".to_string()));
        // raw snake_case kept as an alias
        assert!(syns.contains(&"sum_of_digits".to_string()));
        // single short cryptic name is rejected (fail-closed for precision)
        assert!(derive_nl_surface("f").is_none());
        assert!(derive_nl_surface("gcd").is_some()); // 3 chars, kept
    }

    /// EMERGENCE (a): the mined STRING op set is DERIVED FROM + EQUAL TO the
    /// engine's `SExpr` unary surface. We iterate the engine's reflected op list
    /// and assert every one appears in the mined output with a matching
    /// `string`->`string` signature; the string_synth exhaustiveness guard (run
    /// here) proves that reflected list is the whole unary `SExpr` arm.
    #[test]
    fn mined_string_surface_equals_engine_sexpr_surface() {
        // The enum-exhaustiveness guard: mined string lemmas == unary SExpr arm.
        crate::string_synth::mineable_string_ops_exhaustive();

        let mined = mine_capabilities();
        let ents = mined["entities"].as_object().unwrap();
        for op in crate::string_synth::mineable_string_ops() {
            let e = ents
                .get(op.lemma)
                .unwrap_or_else(|| panic!("engine op {} not mined", op.lemma));
            let attrs = &e["attributes"];
            assert_eq!(
                attrs["input_types"], "string",
                "{} mined with wrong input_types",
                op.lemma
            );
            assert_eq!(
                attrs["output_type"], "string",
                "{} mined with wrong output_type",
                op.lemma
            );
            // Provenance proves it came from the engine symbol table.
            assert_eq!(attrs["mined_provenance"], "string_synth::SExpr");
        }
    }

    /// EMERGENCE (a) for arrays: mined array op set == `ReorderKind` surface.
    #[test]
    fn mined_array_surface_equals_engine_reorderkind_surface() {
        let mined = mine_capabilities();
        let ents = mined["entities"].as_object().unwrap();
        for op in crate::synthesis::array_transform::mineable_array_ops() {
            let e = ents
                .get(op.lemma)
                .unwrap_or_else(|| panic!("engine array op {} not mined", op.lemma));
            assert_eq!(e["attributes"]["input_types"], "Vec<i64>");
            assert_eq!(e["attributes"]["output_type"], "Vec<i64>");
            assert_eq!(
                e["attributes"]["mined_provenance"],
                "array_transform::ReorderKind"
            );
        }
    }

    /// EMERGENCE (b): example_cases are AUTO-GENERATED by RUNNING the op. We
    /// re-run the REAL evaluator on the mined inputs and assert the mined
    /// `expected` equals the freshly-computed output — so the examples provably
    /// came from executing the op, not from a hand table.
    #[test]
    fn mined_examples_match_op_executed() {
        let mined = mine_capabilities();
        let ents = mined["entities"].as_object().unwrap();

        // Sample mined STRING op: lowercase.
        let lower_run = crate::string_synth::mineable_string_ops()
            .into_iter()
            .find(|o| o.lemma == "lowercase")
            .unwrap()
            .run;
        let cases_str = ents["lowercase"]["attributes"]["example_cases"]
            .as_str()
            .unwrap();
        let cases: Value = serde_json::from_str(cases_str).unwrap();
        for case in cases.as_array().unwrap() {
            let input = case["inputs"][0]["value"].as_str().unwrap();
            let expected = case["expected"]["value"].as_str().unwrap();
            assert_eq!(
                lower_run(input).as_deref(),
                Some(expected),
                "mined lowercase example for {input:?} != op executed"
            );
            // And it must NOT be the identity (proves a real transform mined).
        }
        // At least one probe must differ from identity (a real op, not echo).
        let any_transformed = cases.as_array().unwrap().iter().any(|c| {
            c["inputs"][0]["value"].as_str() != c["expected"]["value"].as_str()
        });
        assert!(any_transformed, "lowercase mined examples are all identity");

        // Sample mined ARRAY op: sort.
        let sort_run = crate::synthesis::array_transform::mineable_array_ops()
            .into_iter()
            .find(|o| o.lemma == "sort")
            .unwrap()
            .run;
        let acases_str = ents["sort"]["attributes"]["example_cases"].as_str().unwrap();
        let acases: Value = serde_json::from_str(acases_str).unwrap();
        for case in acases.as_array().unwrap() {
            let input: Vec<i64> = case["inputs"][0]["value"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_i64().unwrap())
                .collect();
            let expected: Vec<i64> = case["expected"]["value"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_i64().unwrap())
                .collect();
            assert_eq!(sort_run(&input), expected, "mined sort example != op executed");
        }
    }

    /// EMERGENCE (c) / DETERMINISM: re-running the miner is byte-identical.
    #[test]
    fn miner_is_deterministic() {
        let a = mine_capabilities_json();
        let b = mine_capabilities_json();
        assert_eq!(a, b, "miner output is not deterministic");
        assert!(a.ends_with('\n'));
    }

    /// HONESTY: side-effecting / non-deterministic / unimplemented ops are NEVER
    /// mined. The runtime exposes file IO (`open_file`/`read_file`/`write_file`)
    /// and process spawn — none of those names may appear as a mined capability,
    /// because the miner only reflects PURE synthesizable op enums.
    #[test]
    fn assert_no_impure_ops_mined() {
        let lemmas = mined_lemmas();
        for impure in [
            "read_file",
            "write_file",
            "open_file",
            "close_file",
            "spawn",
            "send",
            "recv",
            "read",
            "print",
            "println",
            "train",
            "train_model",
        ] {
            assert!(
                !lemmas.contains(&impure.to_string()),
                "impure/unimplemented op {impure} must NOT be mined"
            );
        }
    }

    /// The miner must produce the NON-seed ops the accept-criterion requires
    /// (`lowercase`, `trim`) plus the order ops it now self-supplies, plus the
    /// NL-BRIDGE-3A widened elementwise-map family.
    #[test]
    fn miner_emits_expected_capabilities() {
        let lemmas = mined_lemmas();
        for needed in [
            "uppercase", "lowercase", "trim", "reverse_string", "sort", "reverse",
            // NL-BRIDGE-3A new elementwise maps:
            "double_each", "negate_each", "increment_each", "square_each", "abs_each",
        ] {
            assert!(
                lemmas.contains(&needed.to_string()),
                "miner missing capability {needed}; mined = {lemmas:?}"
            );
        }
    }

    /// EMERGENCE (a) for the NL-BRIDGE-3A elementwise-map family: the mined op set
    /// is DERIVED FROM + EQUAL TO the engine's `ElementMapKind` enum surface, and
    /// every variant is also EMITTED as a candidate by the solver's candidate
    /// builder (so the mined surface == the engine's emitted surface). Adding a
    /// variant to the enum without classifying it fails to COMPILE the guard.
    #[test]
    fn mined_element_map_surface_equals_engine_enum_surface() {
        // The enum-exhaustiveness guard: mined element-map lemmas == ElementMapKind.
        crate::synthesis::array_transform::mineable_element_map_ops_exhaustive();

        let mined = mine_capabilities();
        let ents = mined["entities"].as_object().unwrap();
        for op in crate::synthesis::array_transform::mineable_element_map_ops() {
            let e = ents
                .get(op.lemma)
                .unwrap_or_else(|| panic!("engine element-map op {} not mined", op.lemma));
            assert_eq!(e["attributes"]["input_types"], "Vec<i64>");
            assert_eq!(e["attributes"]["output_type"], "Vec<i64>");
            assert_eq!(
                e["attributes"]["mined_provenance"],
                "array_transform::ElementMapKind"
            );
        }
    }

    /// EMERGENCE (b) for the elementwise-map family: example_cases are
    /// AUTO-GENERATED by RUNNING the op. Re-run the REAL `element_apply` on the
    /// mined inputs and assert the mined `expected` equals the freshly-computed
    /// output — so the examples provably came from executing the op, and at least
    /// one row is a genuine (non-identity) transform.
    #[test]
    fn mined_element_map_examples_match_op_executed() {
        let mined = mine_capabilities();
        let ents = mined["entities"].as_object().unwrap();
        for op in crate::synthesis::array_transform::mineable_element_map_ops() {
            let cases_str = ents[op.lemma]["attributes"]["example_cases"].as_str().unwrap();
            let cases: Value = serde_json::from_str(cases_str).unwrap();
            let arr = cases.as_array().unwrap();
            assert!(arr.len() >= 3, "{} mined <3 example rows", op.lemma);
            let mut any_transform = false;
            for case in arr {
                let input: Vec<i64> = case["inputs"][0]["value"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_i64().unwrap())
                    .collect();
                let expected: Vec<i64> = case["expected"]["value"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_i64().unwrap())
                    .collect();
                assert_eq!(
                    (op.run)(&input),
                    expected,
                    "mined {} example != op executed",
                    op.lemma
                );
                if input != expected {
                    any_transform = true;
                }
            }
            assert!(any_transform, "{} mined examples are all identity", op.lemma);
        }
    }
}
