//! Capability AUTO-MINER (NL-BRIDGE-2-AUTO-MINER).
//!
//! Reflects the engine's OWN synthesizable operator surface into capability
//! Entity records (the JSON the NL bridge loads through the existing
//! `coding_registry.json` seam), so the NL vocabulary becomes EMERGENT and
//! self-growing instead of a hand-typed phrase->op table.
//!
//! WHY THIS IS EMERGENT, NOT A HAND LIST:
//!   * The op SET is reflected from the engine symbol tables —
//!     `string_synth::mineable_string_ops()` (derived from the `SExpr` enum) and
//!     `synthesis::array_transform::mineable_array_ops()` (derived from the
//!     `ReorderKind` enum). Add an operator variant to either enum + re-run the
//!     miner and the capability appears with NO hand edit; the exhaustive `match`
//!     guards in those modules fail closed if a new variant is left unclassified.
//!   * Each op's `example_cases` are AUTO-GENERATED by RUNNING the op's REAL
//!     evaluator (`eval_s` / the order-op semantics) on canonical inputs — the
//!     same "run the code to manufacture teacher examples" trick used by
//!     `teacher_examples_from_code` (differentiable.rs:249). No expected output
//!     is hand-written.
//!   * Only PURE + DETERMINISTIC + auto-verifiable ops are emitted. Side-effecting
//!     / non-deterministic / unimplemented ops are NEVER mined (see
//!     `assert_no_impure_ops_mined` in the tests), so the fail-closed NL gate is
//!     never handed a capability the engine cannot synthesize + verify.
//!
//! The miner is an OFFLINE build step (run via the `mine_capabilities` bin or a
//! test) that produces a COMMITTED JSON file in the SAME schema as
//! `coding_registry.json`; the runtime stays pure-Rust and merely loads it via
//! the existing `Registry::from_json` path. Re-running the miner is byte-stable.

use serde_json::{json, Value};

/// Canonical input strings the string ops are exercised on to manufacture
/// example_cases. Every probe carries BOTH surrounding whitespace AND mixed case
/// AND length > 1, so that EVERY mined op (`trim`, `lowercase`, `uppercase`,
/// `reverse_string`) produces a NON-identity, mutually-distinct output on the
/// whole set — otherwise a faster specialist (e.g. the suffix-conditioned
/// `morph_transduce`) can overfit a degenerate rule on the identity-heavy rows.
/// The set yields >=3 DISTINCT (input,output) rows for every op so the bridge's
/// fresh-holdout differential check always has a held-out probe.
const STRING_PROBES: &[&str] = &[
    " Hello ",
    "World ",
    " AbC",
    "MiXeD ",
    " nSynth ",
    "  Xy  ",
];

/// Canonical input arrays the array order ops are exercised on.
const ARRAY_PROBES: &[&[i64]] = &[&[3, 1, 2], &[5, 4, 6, 4], &[1], &[2, 2, 1, 3]];

/// Hand-authored NL surface FORMS (synonyms + a one-line gloss) per mined lemma.
/// These are presentation metadata for the comprehension layer — NOT the op set
/// or its behaviour (both of which are reflected + auto-run). The lemma keys are
/// asserted to be EXACTLY the reflected engine surface in the tests, so this map
/// cannot smuggle in an op the engine does not actually expose.
fn nl_surface(lemma: &str) -> (Vec<&'static str>, &'static str, &'static str) {
    // (synonyms, definition, domain)
    match lemma {
        "uppercase" => (
            vec!["uppercased", "upcase", "capitalize_all"],
            "Convert every character of a string to upper case",
            "string",
        ),
        "lowercase" => (
            vec!["lowercased", "downcase"],
            "Convert every character of a string to lower case",
            "string",
        ),
        "trim" => (
            vec!["strip", "trimmed"],
            "Remove leading and trailing whitespace from a string",
            "string",
        ),
        "reverse_string" => (
            vec!["reversed_string"],
            "Reverse the characters of a string",
            "string",
        ),
        "sort" => (
            vec!["sorted", "order"],
            "Sort array in ascending order",
            "array",
        ),
        "reverse" => (
            vec!["reversed"],
            "Reverse order of array elements",
            "array",
        ),
        _ => (vec![], "", "unknown"),
    }
}

/// Build the `example_cases` JSON string for a string op by RUNNING its real
/// evaluator on the canonical probes. De-dups by (input,output) so the rows are
/// distinct, and skips inputs the op cannot evaluate (never happens for the
/// total string ops, but kept honest).
fn string_example_cases(run: fn(&str) -> Option<String>) -> Option<String> {
    let mut cases: Vec<Value> = Vec::new();
    let mut seen: std::collections::HashSet<(String, String)> = std::collections::HashSet::new();
    for &probe in STRING_PROBES {
        let out = run(probe)?; // auto-run the REAL op
        if seen.insert((probe.to_string(), out.clone())) {
            cases.push(json!({
                "inputs": [{"type": "Str", "value": probe}],
                "expected": {"type": "Str", "value": out},
            }));
        }
    }
    if cases.len() < 3 {
        return None; // too thin to be a sound, holdout-protected capability
    }
    Some(Value::Array(cases).to_string())
}

/// Build the `example_cases` JSON string for an array order op by RUNNING its real
/// semantics on the canonical probe arrays.
fn array_example_cases(run: fn(&[i64]) -> Vec<i64>) -> Option<String> {
    let mut cases: Vec<Value> = Vec::new();
    let mut seen: std::collections::HashSet<(Vec<i64>, Vec<i64>)> = std::collections::HashSet::new();
    for &probe in ARRAY_PROBES {
        let out = run(probe); // auto-run the REAL op
        if seen.insert((probe.to_vec(), out.clone())) {
            cases.push(json!({
                "inputs": [{"type": "Array", "value": probe}],
                "expected": {"type": "Array", "value": out},
            }));
        }
    }
    if cases.len() < 3 {
        return None;
    }
    Some(Value::Array(cases).to_string())
}

/// One mined capability, ready to serialize into the `coding_registry.json`
/// schema (entity = lemma -> {word, entity_type, definitions, attributes,
/// relations}). Built ENTIRELY from reflected engine data + auto-run examples.
fn string_entity(
    lemma: &str,
    code_body: &str,
    example_cases: String,
) -> (String, Value) {
    let (syns, def, domain) = nl_surface(lemma);
    // Derive the default fn-name/category from the engine signature, not by hand:
    // every string op here is arity-1 `string -> string`.
    let attrs = json!({
        "arity": "1",
        "input_types": "string",
        "output_type": "string",
        "nsynth_category": "string",
        "default_fn_name": "transform",
        "signature_template": "fn {name}({params}) -> {return}",
        // Provenance: the engine codegen body this op corresponds to (e.g.
        // `s.lower()`), and that the example_cases were machine-mined.
        "mined_engine_codegen": code_body,
        "mined_provenance": "string_synth::SExpr",
        "example_cases": example_cases,
    });
    let entity = json!({
        "word": lemma,
        "entity_type": "function",
        "definitions": [def],
        "attributes": attrs,
        "relations": {
            "synonym": syns,
            "domain": [domain],
        },
    });
    (lemma.to_string(), entity)
}

fn array_entity(lemma: &str, example_cases: String) -> (String, Value) {
    let (syns, def, domain) = nl_surface(lemma);
    let attrs = json!({
        "arity": "1",
        "input_types": "Vec<i64>",
        "output_type": "Vec<i64>",
        "nsynth_category": "array",
        "default_fn_name": lemma,
        "signature_template": "fn {name}({params}) -> {return}",
        "mined_provenance": "array_transform::ReorderKind",
        "example_cases": example_cases,
    });
    let entity = json!({
        "word": lemma,
        "entity_type": "function",
        "definitions": [def],
        "attributes": attrs,
        "relations": {
            "synonym": syns,
            "domain": [domain],
        },
    });
    (lemma.to_string(), entity)
}

/// Reflect the engine operator surface + auto-run for examples, producing the
/// mined capability registry as a `serde_json::Value` in `coding_registry.json`
/// schema. PURE + DETERMINISTIC: same engine surface -> byte-identical output
/// (entities emitted in a fixed, sorted order; `serde_json::Map` is a BTreeMap so
/// keys are ordered).
pub fn mine_capabilities() -> Value {
    let mut entities = serde_json::Map::new();

    // ── STRING ops — reflected from string_synth's SExpr enum ────────────────
    let mut string_ops = crate::string_synth::mineable_string_ops();
    // Stable order independent of declaration order.
    string_ops.sort_by(|a, b| a.lemma.cmp(b.lemma));
    for op in string_ops {
        // HONEST: only emit if the op auto-verifies to >=3 distinct example rows.
        if let Some(cases) = string_example_cases(op.run) {
            let (k, v) = string_entity(op.lemma, &op.code_body, cases);
            entities.insert(k, v);
        }
    }

    // ── ARRAY order ops — reflected from array_transform's ReorderKind enum ───
    let mut array_ops = crate::synthesis::array_transform::mineable_array_ops();
    array_ops.sort_by(|a, b| a.lemma.cmp(b.lemma));
    for op in array_ops {
        if let Some(cases) = array_example_cases(op.run) {
            let (k, v) = array_entity(op.lemma, cases);
            entities.insert(k, v);
        }
    }

    json!({
        "_generated": "AUTO-MINED by capability_miner::mine_capabilities — do not edit by hand",
        "entities": Value::Object(entities),
    })
}

/// Serialize the mined registry to a stable, pretty JSON string (newline-
/// terminated). Byte-identical across runs for a fixed engine surface.
pub fn mine_capabilities_json() -> String {
    let mut s = serde_json::to_string_pretty(&mine_capabilities()).expect("serialize mined caps");
    s.push('\n');
    s
}

/// The set of lemmas the miner currently emits (for tests + the
/// remove-now-covered-seeds bookkeeping).
pub fn mined_lemmas() -> Vec<String> {
    let v = mine_capabilities();
    v.get("entities")
        .and_then(|e| e.as_object())
        .map(|m| m.keys().cloned().collect())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// EMERGENCE (a): the mined STRING op set is DERIVED FROM + EQUAL TO the
    /// engine's `SExpr` unary surface. We iterate the engine's reflected op list
    /// and assert every one appears in the mined output with a matching
    /// `string`->`string` signature; the string_synth exhaustiveness guard (run
    /// here) proves that reflected list is the whole unary `SExpr` arm.
    #[test]
    fn mined_string_surface_equals_engine_sexpr_surface() {
        // The enum-exhaustiveness guard: mined string lemmas == unary SExpr arm.
        crate::string_synth::mineable_string_ops_exhaustive();

        let mined = mine_capabilities();
        let ents = mined["entities"].as_object().unwrap();
        for op in crate::string_synth::mineable_string_ops() {
            let e = ents
                .get(op.lemma)
                .unwrap_or_else(|| panic!("engine op {} not mined", op.lemma));
            let attrs = &e["attributes"];
            assert_eq!(
                attrs["input_types"], "string",
                "{} mined with wrong input_types",
                op.lemma
            );
            assert_eq!(
                attrs["output_type"], "string",
                "{} mined with wrong output_type",
                op.lemma
            );
            // Provenance proves it came from the engine symbol table.
            assert_eq!(attrs["mined_provenance"], "string_synth::SExpr");
        }
    }

    /// EMERGENCE (a) for arrays: mined array op set == `ReorderKind` surface.
    #[test]
    fn mined_array_surface_equals_engine_reorderkind_surface() {
        let mined = mine_capabilities();
        let ents = mined["entities"].as_object().unwrap();
        for op in crate::synthesis::array_transform::mineable_array_ops() {
            let e = ents
                .get(op.lemma)
                .unwrap_or_else(|| panic!("engine array op {} not mined", op.lemma));
            assert_eq!(e["attributes"]["input_types"], "Vec<i64>");
            assert_eq!(e["attributes"]["output_type"], "Vec<i64>");
            assert_eq!(
                e["attributes"]["mined_provenance"],
                "array_transform::ReorderKind"
            );
        }
    }

    /// EMERGENCE (b): example_cases are AUTO-GENERATED by RUNNING the op. We
    /// re-run the REAL evaluator on the mined inputs and assert the mined
    /// `expected` equals the freshly-computed output — so the examples provably
    /// came from executing the op, not from a hand table.
    #[test]
    fn mined_examples_match_op_executed() {
        let mined = mine_capabilities();
        let ents = mined["entities"].as_object().unwrap();

        // Sample mined STRING op: lowercase.
        let lower_run = crate::string_synth::mineable_string_ops()
            .into_iter()
            .find(|o| o.lemma == "lowercase")
            .unwrap()
            .run;
        let cases_str = ents["lowercase"]["attributes"]["example_cases"]
            .as_str()
            .unwrap();
        let cases: Value = serde_json::from_str(cases_str).unwrap();
        for case in cases.as_array().unwrap() {
            let input = case["inputs"][0]["value"].as_str().unwrap();
            let expected = case["expected"]["value"].as_str().unwrap();
            assert_eq!(
                lower_run(input).as_deref(),
                Some(expected),
                "mined lowercase example for {input:?} != op executed"
            );
            // And it must NOT be the identity (proves a real transform mined).
        }
        // At least one probe must differ from identity (a real op, not echo).
        let any_transformed = cases.as_array().unwrap().iter().any(|c| {
            c["inputs"][0]["value"].as_str() != c["expected"]["value"].as_str()
        });
        assert!(any_transformed, "lowercase mined examples are all identity");

        // Sample mined ARRAY op: sort.
        let sort_run = crate::synthesis::array_transform::mineable_array_ops()
            .into_iter()
            .find(|o| o.lemma == "sort")
            .unwrap()
            .run;
        let acases_str = ents["sort"]["attributes"]["example_cases"].as_str().unwrap();
        let acases: Value = serde_json::from_str(acases_str).unwrap();
        for case in acases.as_array().unwrap() {
            let input: Vec<i64> = case["inputs"][0]["value"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_i64().unwrap())
                .collect();
            let expected: Vec<i64> = case["expected"]["value"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_i64().unwrap())
                .collect();
            assert_eq!(sort_run(&input), expected, "mined sort example != op executed");
        }
    }

    /// EMERGENCE (c) / DETERMINISM: re-running the miner is byte-identical.
    #[test]
    fn miner_is_deterministic() {
        let a = mine_capabilities_json();
        let b = mine_capabilities_json();
        assert_eq!(a, b, "miner output is not deterministic");
        assert!(a.ends_with('\n'));
    }

    /// HONESTY: side-effecting / non-deterministic / unimplemented ops are NEVER
    /// mined. The runtime exposes file IO (`open_file`/`read_file`/`write_file`)
    /// and process spawn — none of those names may appear as a mined capability,
    /// because the miner only reflects PURE synthesizable op enums.
    #[test]
    fn assert_no_impure_ops_mined() {
        let lemmas = mined_lemmas();
        for impure in [
            "read_file",
            "write_file",
            "open_file",
            "close_file",
            "spawn",
            "send",
            "recv",
            "read",
            "print",
            "println",
            "train",
            "train_model",
        ] {
            assert!(
                !lemmas.contains(&impure.to_string()),
                "impure/unimplemented op {impure} must NOT be mined"
            );
        }
    }

    /// The miner must produce the NON-seed ops the accept-criterion requires
    /// (`lowercase`, `trim`) plus the order ops it now self-supplies.
    #[test]
    fn miner_emits_expected_capabilities() {
        let lemmas = mined_lemmas();
        for needed in ["uppercase", "lowercase", "trim", "reverse_string", "sort", "reverse"] {
            assert!(
                lemmas.contains(&needed.to_string()),
                "miner missing capability {needed}; mined = {lemmas:?}"
            );
        }
    }
}
