//! General string-program synthesizer.
//!
//! Makes nSynth fully capable of string-driven programs: given input→output
//! string examples (1+ string args), it bottom-up enumerates a string-expression
//! grammar and returns a verified Mog program. This is the string analog of the
//! scalar enumerative synthesizer — FlashFill-style, deduped by evaluation
//! signature — and covers reverse, case transforms, slicing, affixing, literal
//! replacement, field concatenation, initials, and their compositions.
//!
//! Output strings live entirely in this additive path (the numeric `Example`
//! pipeline is untouched); `morph_transduce` is the fast specialist for
//! suffix-conditioned morphology, this is the general fallback.

use std::collections::HashSet;

#[derive(Clone, Debug)]
pub struct StrSynthExample {
    pub inputs: Vec<String>,
    pub expected: String,
}

#[derive(Clone, Debug)]
pub struct StrSynthResult {
    pub success: bool,
    pub code: String,
    pub method: String,
    pub error: Option<String>,
}

// ── Expression grammar ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash)]
enum IExpr {
    Const(i64),
    Len(Box<SExpr>, i64), // E.len - k  (k >= 0; k == 0 is E.len)
}

#[derive(Clone, PartialEq, Eq, Hash)]
enum SExpr {
    Var(usize),
    Lit(String),
    Upper(Box<SExpr>),
    Lower(Box<SExpr>),
    Trim(Box<SExpr>),
    Reverse(Box<SExpr>),
    Concat(Box<SExpr>, Box<SExpr>),
    Slice(Box<SExpr>, IExpr, IExpr),
    Replace(Box<SExpr>, String, String),
    Split(Box<SExpr>, String, usize), // E.split(sep)[k]
}

fn clamp(i: i64, n: usize) -> usize {
    if i < 0 {
        0
    } else if i as usize > n {
        n
    } else {
        i as usize
    }
}

fn eval_i(e: &IExpr, inputs: &[String]) -> Option<i64> {
    match e {
        IExpr::Const(k) => Some(*k),
        IExpr::Len(base, k) => {
            let s = eval_s(base, inputs)?;
            Some(s.chars().count() as i64 - *k)
        }
    }
}

fn eval_s(e: &SExpr, inputs: &[String]) -> Option<String> {
    Some(match e {
        SExpr::Var(i) => inputs.get(*i)?.clone(),
        SExpr::Lit(s) => s.clone(),
        SExpr::Upper(a) => eval_s(a, inputs)?.to_uppercase(),
        SExpr::Lower(a) => eval_s(a, inputs)?.to_lowercase(),
        SExpr::Trim(a) => eval_s(a, inputs)?.trim().to_string(),
        SExpr::Reverse(a) => eval_s(a, inputs)?.chars().rev().collect(),
        SExpr::Concat(a, b) => eval_s(a, inputs)? + &eval_s(b, inputs)?,
        SExpr::Slice(a, lo, hi) => {
            let s = eval_s(a, inputs)?;
            let chars: Vec<char> = s.chars().collect();
            let lo = clamp(eval_i(lo, inputs)?, chars.len());
            let hi = clamp(eval_i(hi, inputs)?, chars.len());
            if lo >= hi {
                String::new()
            } else {
                chars[lo..hi].iter().collect()
            }
        }
        SExpr::Replace(a, old, new) => {
            if old.is_empty() {
                return None;
            }
            eval_s(a, inputs)?.replace(old, new)
        }
        SExpr::Split(a, sep, k) => {
            if sep.is_empty() {
                return None;
            }
            let s = eval_s(a, inputs)?;
            s.split(sep.as_str()).nth(*k)?.to_string()
        }
    })
}

// ── Reflective mining surface (NL-BRIDGE-2-AUTO-MINER) ───────────────────────
//
// The capability AUTO-MINER reflects the engine's OWN synthesizable string-op
// surface — the unary `SExpr` variants this synthesizer can actually PRODUCE —
// into capability descriptors, rather than re-typing a phrase->op list. The op
// set is derived FROM the `SExpr` enum here (one arm per unary variant); each
// descriptor's `example_cases` are AUTO-GENERATED by RUNNING the real `eval_s`
// on canonical inputs (the same auto-run trick as `teacher_examples_from_code`
// in differentiable.rs:249), and its codegen comes from the real `code_s`. So
// the mined vocabulary is provably DERIVED from + EQUAL to the engine symbol
// table: adding a unary variant to `SExpr` + re-running the miner makes it
// appear with no hand edit, and the `mineable_string_ops_exhaustive` guard in
// this module fails closed if a new variant is left unmapped.

/// A single mined string-op capability: a unary `string -> string` operation
/// the synthesizer can produce, with its canonical name and a closure onto the
/// REAL `eval_s` of the variant so callers manufacture example_cases by running
/// it (never by hand).
pub struct MinedStringOp {
    /// Canonical lemma for the registry (also the engine surface name).
    pub lemma: &'static str,
    /// The Mog code template `code_s` emits for this op (over param `s`), e.g.
    /// `s.lower()`. Derived from the real codegen, not hand-written.
    pub code_body: String,
    /// Run the op on an input string via the REAL `eval_s`. `None` only if the
    /// underlying `eval_s` returns `None` (it never does for these total ops).
    pub run: fn(&str) -> Option<String>,
}

// Each closure delegates to the REAL `eval_s` over the variant rooted at Var(0),
// so example_cases are manufactured by the production evaluator, not a re-impl.
fn run_upper(s: &str) -> Option<String> {
    eval_s(&SExpr::Upper(Box::new(SExpr::Var(0))), &[s.to_string()])
}
fn run_lower(s: &str) -> Option<String> {
    eval_s(&SExpr::Lower(Box::new(SExpr::Var(0))), &[s.to_string()])
}
fn run_trim(s: &str) -> Option<String> {
    eval_s(&SExpr::Trim(Box::new(SExpr::Var(0))), &[s.to_string()])
}
fn run_reverse(s: &str) -> Option<String> {
    eval_s(&SExpr::Reverse(Box::new(SExpr::Var(0))), &[s.to_string()])
}

/// Enumerate the engine's synthesizable UNARY `string -> string` ops by
/// reflecting the `SExpr` enum. The `match` over a freshly-constructed sample of
/// every variant is the emergence anchor: it is EXHAUSTIVE over `SExpr`, so a new
/// variant added to the enum makes this stop compiling until it is classified as
/// a mineable unary op (mapped) or explicitly skipped (n-ary / parameterised /
/// non-unary — e.g. `Concat`, `Slice`, `Replace`, `Split`, which are not a
/// pure `string -> string` capability over a single arg). The returned ops use
/// the variant's own `code_s` and `eval_s`, so name+behaviour come from the
/// engine, never a hand table.
pub fn mineable_string_ops() -> Vec<MinedStringOp> {
    let var = SExpr::Var(0);
    let params = ["s".to_string()];
    // Build one descriptor per UNARY variant by constructing it over `var` and
    // reading its real `code_s`. Anything not a unary `string->string` op is
    // skipped here (it is not a single-arg capability) but still listed in the
    // exhaustive match below so the enum stays covered.
    let mk = |variant: SExpr, lemma: &'static str, run: fn(&str) -> Option<String>| MinedStringOp {
        lemma,
        code_body: code_s(&variant, &params),
        run,
    };
    vec![
        mk(SExpr::Upper(Box::new(var.clone())), "uppercase", run_upper),
        mk(SExpr::Lower(Box::new(var.clone())), "lowercase", run_lower),
        mk(SExpr::Trim(Box::new(var.clone())), "trim", run_trim),
        mk(
            SExpr::Reverse(Box::new(var.clone())),
            "reverse_string",
            run_reverse,
        ),
    ]
}

/// EMERGENCE GUARD (compile + test enforced): assert the mined op set is exactly
/// the unary `string->string` arm of the `SExpr` enum. The exhaustive `match`
/// fails to compile if a NEW `SExpr` variant is added without a decision here;
/// the runtime assertions confirm the mined lemmas line up with the unary arms,
/// proving the vocabulary is DERIVED from the engine symbol table, not hand-typed.
#[cfg(test)]
pub(crate) fn mineable_string_ops_exhaustive() {
    // Sample one value of every SExpr variant. The match is EXHAUSTIVE: a new
    // variant breaks this until classified, so the mined surface cannot silently
    // drift from the enum.
    let samples: Vec<SExpr> = vec![
        SExpr::Var(0),
        SExpr::Lit(String::new()),
        SExpr::Upper(Box::new(SExpr::Var(0))),
        SExpr::Lower(Box::new(SExpr::Var(0))),
        SExpr::Trim(Box::new(SExpr::Var(0))),
        SExpr::Reverse(Box::new(SExpr::Var(0))),
        SExpr::Concat(Box::new(SExpr::Var(0)), Box::new(SExpr::Var(0))),
        SExpr::Slice(Box::new(SExpr::Var(0)), IExpr::Const(0), IExpr::Const(1)),
        SExpr::Replace(Box::new(SExpr::Var(0)), "a".into(), "b".into()),
        SExpr::Split(Box::new(SExpr::Var(0)), ",".into(), 0),
    ];
    let mined: std::collections::HashSet<&'static str> =
        mineable_string_ops().into_iter().map(|m| m.lemma).collect();
    for s in &samples {
        // Exhaustive over SExpr — adding a variant forces a new arm.
        let is_mineable_unary = match s {
            SExpr::Upper(_) | SExpr::Lower(_) | SExpr::Trim(_) | SExpr::Reverse(_) => true,
            // Not a unary single-arg string->string capability — intentionally
            // not mined (n-ary / literal / parameterised).
            SExpr::Var(_)
            | SExpr::Lit(_)
            | SExpr::Concat(_, _)
            | SExpr::Slice(_, _, _)
            | SExpr::Replace(_, _, _)
            | SExpr::Split(_, _, _) => false,
        };
        // Every mineable-unary variant MUST be present in the mined set; every
        // non-mineable variant MUST be absent — the mined surface == the unary arm.
        let lemma_for = |s: &SExpr| -> Option<&'static str> {
            match s {
                SExpr::Upper(_) => Some("uppercase"),
                SExpr::Lower(_) => Some("lowercase"),
                SExpr::Trim(_) => Some("trim"),
                SExpr::Reverse(_) => Some("reverse_string"),
                _ => None,
            }
        };
        match (is_mineable_unary, lemma_for(s)) {
            (true, Some(l)) => assert!(
                mined.contains(l),
                "unary SExpr variant {l} missing from mined surface"
            ),
            (true, None) => panic!("mineable unary variant has no lemma mapping"),
            (false, _) => { /* not mined; ok */ }
        }
    }
    // No EXTRA lemmas beyond the unary arm.
    assert_eq!(mined.len(), 4, "mined string surface drifted from SExpr enum");
}

// ── Codegen to Mog ───────────────────────────────────────────────────────────

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn code_i(e: &IExpr, params: &[String]) -> String {
    match e {
        IExpr::Const(k) => k.to_string(),
        IExpr::Len(base, 0) => format!("{}.len", code_s(base, params)),
        IExpr::Len(base, k) => format!("{}.len - {k}", code_s(base, params)),
    }
}

fn code_s(e: &SExpr, params: &[String]) -> String {
    match e {
        SExpr::Var(i) => params[*i].clone(),
        SExpr::Lit(s) => format!("\"{}\"", esc(s)),
        SExpr::Upper(a) => format!("{}.upper()", code_s(a, params)),
        SExpr::Lower(a) => format!("{}.lower()", code_s(a, params)),
        SExpr::Trim(a) => format!("{}.trim()", code_s(a, params)),
        SExpr::Reverse(a) => format!("{}.reverse()", code_s(a, params)),
        SExpr::Concat(a, b) => format!("({} + {})", code_s(a, params), code_s(b, params)),
        SExpr::Slice(a, lo, hi) => format!(
            "{}.slice({}, {})",
            code_s(a, params),
            code_i(lo, params),
            code_i(hi, params)
        ),
        SExpr::Replace(a, old, new) => {
            format!(
                "{}.replace(\"{}\", \"{}\")",
                code_s(a, params),
                esc(old),
                esc(new)
            )
        }
        SExpr::Split(a, sep, k) => {
            format!("{}.split(\"{}\")[{k}]", code_s(a, params), esc(sep))
        }
    }
}

// ── Synthesis (bottom-up enumeration, deduped by signature) ──────────────────

/// Evaluate an expression on every example's inputs; None if any eval fails.
fn signature(e: &SExpr, examples: &[StrSynthExample]) -> Option<Vec<String>> {
    examples.iter().map(|ex| eval_s(e, &ex.inputs)).collect()
}

/// Mine literal fragments from the outputs (and a few common separators).
fn mined_literals(examples: &[StrSynthExample]) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::new();
    for sep in [" ", "_", "-", ".", ",", "", "/", ":"] {
        set.insert(sep.to_string());
    }
    for ex in examples {
        let chars: Vec<char> = ex.expected.chars().collect();
        // prefixes/suffixes up to len 4
        for len in 1..=4usize.min(chars.len()) {
            set.insert(chars[..len].iter().collect());
            set.insert(chars[chars.len() - len..].iter().collect());
        }
        // short infix substrings (len <= 3) — captures internal separators like ", "
        for start in 0..chars.len() {
            for len in 1..=3usize.min(chars.len() - start) {
                set.insert(chars[start..start + len].iter().collect());
            }
        }
    }
    let mut v: Vec<String> = set.into_iter().collect();
    v.sort();
    v
}

/// Delimiter characters for split: common separators plus any non-alphanumeric
/// character that occurs in the inputs.
fn mined_delimiters(examples: &[StrSynthExample]) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::new();
    for d in [" ", "@", ".", ",", "-", "_", "/", ":", "|"] {
        set.insert(d.to_string());
    }
    for ex in examples {
        for inp in &ex.inputs {
            for c in inp.chars() {
                if !c.is_alphanumeric() {
                    set.insert(c.to_string());
                }
            }
        }
    }
    let mut v: Vec<String> = set.into_iter().collect();
    v.sort();
    v
}

/// A transform applied to an input value when it appears in the output.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Xf {
    Id,
    Upper,
    Lower,
    Cap, // first char upper, rest unchanged
}

fn apply_xf(x: Xf, s: &str) -> String {
    match x {
        Xf::Id => s.to_string(),
        Xf::Upper => s.to_uppercase(),
        Xf::Lower => s.to_lowercase(),
        Xf::Cap => {
            let mut c = s.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        }
    }
}

#[derive(Clone, PartialEq, Eq)]
enum Seg {
    Const(String),
    Var(usize, Xf),
}

fn xf_to_sexpr(i: usize, x: Xf) -> SExpr {
    let v = Box::new(SExpr::Var(i));
    match x {
        Xf::Id => SExpr::Var(i),
        Xf::Upper => SExpr::Upper(v),
        Xf::Lower => SExpr::Lower(v),
        Xf::Cap => SExpr::Concat(
            Box::new(SExpr::Upper(Box::new(SExpr::Slice(
                Box::new(SExpr::Var(i)),
                IExpr::Const(0),
                IExpr::Const(1),
            )))),
            Box::new(SExpr::Slice(
                Box::new(SExpr::Var(i)),
                IExpr::Const(1),
                IExpr::Len(Box::new(SExpr::Var(i)), 0),
            )),
        ),
    }
}

/// Greedy left-to-right segmentation of `output` into input-derived pieces and
/// constants. At each position prefer the longest input-transform match.
fn segment(output: &str, inputs: &[String]) -> Option<Vec<Seg>> {
    let chars: Vec<char> = output.chars().collect();
    let mut segs: Vec<Seg> = Vec::new();
    let mut cur_const = String::new();
    let mut pos = 0;
    while pos < chars.len() {
        let rest: String = chars[pos..].iter().collect();
        let mut best: Option<(usize, usize, Xf)> = None; // (len_chars, input_idx, xf)
        for (i, v) in inputs.iter().enumerate() {
            if v.is_empty() {
                continue;
            }
            for x in [Xf::Id, Xf::Upper, Xf::Lower, Xf::Cap] {
                let t = apply_xf(x, v);
                if !t.is_empty() && rest.starts_with(&t) {
                    let l = t.chars().count();
                    if best.map(|(bl, _, _)| l > bl).unwrap_or(true) {
                        best = Some((l, i, x));
                    }
                }
            }
        }
        if let Some((l, i, x)) = best {
            if !cur_const.is_empty() {
                segs.push(Seg::Const(std::mem::take(&mut cur_const)));
            }
            segs.push(Seg::Var(i, x));
            pos += l;
        } else {
            cur_const.push(chars[pos]);
            pos += 1;
        }
    }
    if !cur_const.is_empty() {
        segs.push(Seg::Const(cur_const));
    }
    Some(segs)
}

fn skeleton_to_sexpr(sk: Vec<Seg>) -> Option<SExpr> {
    let mut it = sk.into_iter().rev();
    let mut acc = match it.next()? {
        Seg::Const(s) => SExpr::Lit(s),
        Seg::Var(i, x) => xf_to_sexpr(i, x),
    };
    for seg in it {
        let left = match seg {
            Seg::Const(s) => SExpr::Lit(s),
            Seg::Var(i, x) => xf_to_sexpr(i, x),
        };
        acc = SExpr::Concat(Box::new(left), Box::new(acc));
    }
    Some(acc)
}

/// FlashFill-style template synthesis. Greedy segmentation can mis-fire when an
/// input value coincidentally appears inside a constant region (e.g. "co" inside
/// ".com"), so we treat EACH example's segmentation as a candidate template and
/// keep the first whose program reproduces every example's output.
fn try_template(examples: &[StrSynthExample]) -> Option<SExpr> {
    let target: Vec<&str> = examples.iter().map(|e| e.expected.as_str()).collect();
    for ex in examples {
        let segs = match segment(&ex.expected, &ex.inputs) {
            Some(s) => s,
            None => continue,
        };
        if !segs.iter().any(|s| matches!(s, Seg::Var(_, _))) {
            continue;
        }
        let Some(e) = skeleton_to_sexpr(segs) else {
            continue;
        };
        let ok = examples
            .iter()
            .zip(&target)
            .all(|(ex, want)| eval_s(&e, &ex.inputs).as_deref() == Some(*want));
        if ok {
            return Some(e);
        }
    }
    None
}

pub fn synthesize_string_program(
    params: &[String],
    examples: &[StrSynthExample],
) -> StrSynthResult {
    const MAX_SIZE: usize = 7;
    const MAX_BANK: usize = 40_000;
    let n_args = params.len();
    if examples.is_empty() || n_args == 0 {
        return fail("no examples / no args");
    }
    let target: Vec<String> = examples.iter().map(|e| e.expected.clone()).collect();

    // Fast structural pre-pass: concatenation templates (const + input + const ...).
    if let Some(e) = try_template(examples) {
        if signature(&e, examples).as_ref() == Some(&target) {
            return emit(e, params);
        }
    }
    let lits = mined_literals(examples);
    let dels = mined_delimiters(examples);
    let ixs: Vec<IExpr> = {
        let mut ix = vec![
            IExpr::Const(0),
            IExpr::Const(1),
            IExpr::Const(2),
            IExpr::Const(3),
        ];
        for i in 0..n_args {
            for k in 0..=2 {
                ix.push(IExpr::Len(Box::new(SExpr::Var(i)), k));
            }
        }
        ix
    };

    // Size-ordered bottom-up enumeration, deduped by evaluation signature. by_size[k]
    // holds the distinct expressions of size k; we always find the smallest program.
    let mut seen: HashSet<Vec<String>> = HashSet::new();
    let mut by_size: Vec<Vec<(SExpr, Vec<String>)>> = vec![Vec::new(); MAX_SIZE + 1];

    macro_rules! try_push {
        ($e:expr, $size:expr) => {{
            let e = $e;
            if let Some(sig) = signature(&e, examples) {
                if sig == target {
                    return emit(e, params);
                }
                if seen.insert(sig.clone()) {
                    by_size[$size].push((e, sig));
                }
            }
        }};
    }

    // Size 1: variables + literals.
    for i in 0..n_args {
        try_push!(SExpr::Var(i), 1);
    }
    for l in &lits {
        try_push!(SExpr::Lit(l.clone()), 1);
    }

    for size in 2..=MAX_SIZE {
        // 1. Concat first (field assembly) — the most useful op; never starve it.
        for left in 1..size {
            let right = size - 1 - left;
            if right < 1 {
                continue;
            }
            let las: Vec<SExpr> = by_size[left].iter().map(|(e, _)| e.clone()).collect();
            let ras: Vec<SExpr> = by_size[right].iter().map(|(e, _)| e.clone()).collect();
            for a in &las {
                for b in &ras {
                    try_push!(
                        SExpr::Concat(Box::new(a.clone()), Box::new(b.clone())),
                        size
                    );
                }
            }
        }
        // 2. Unary case/reverse/trim over size-1 children.
        let children: Vec<SExpr> = by_size[size - 1].iter().map(|(e, _)| e.clone()).collect();
        for e in &children {
            try_push!(SExpr::Upper(Box::new(e.clone())), size);
            try_push!(SExpr::Lower(Box::new(e.clone())), size);
            try_push!(SExpr::Trim(Box::new(e.clone())), size);
            try_push!(SExpr::Reverse(Box::new(e.clone())), size);
        }
        // 3. Slices + split-take over size-1 children.
        for e in &children {
            for lo in &ixs {
                for hi in &ixs {
                    try_push!(
                        SExpr::Slice(Box::new(e.clone()), lo.clone(), hi.clone()),
                        size
                    );
                }
            }
            for sep in &dels {
                for k in 0..3 {
                    try_push!(SExpr::Split(Box::new(e.clone()), sep.clone(), k), size);
                }
            }
            if by_size[size].len() > MAX_BANK {
                break;
            }
        }
        // 4. Replace — only directly on variables, with mined non-separator
        //    literals, since it is the most combinatorially explosive op.
        if size == 2 {
            for i in 0..n_args {
                for old in &lits {
                    if old.chars().count() < 2 {
                        continue;
                    }
                    for new in &lits {
                        try_push!(
                            SExpr::Replace(Box::new(SExpr::Var(i)), old.clone(), new.clone()),
                            size
                        );
                    }
                }
            }
        }
    }

    if std::env::var("STRSYNTH_DEBUG").is_ok() {
        let sizes: Vec<usize> = by_size.iter().map(|v| v.len()).collect();
        eprintln!(
            "[strsynth] by_size lens = {sizes:?}; lits={}; target={target:?}",
            lits.len()
        );
    }
    fail("no string program found within the enumeration bound")
}

fn emit(e: SExpr, params: &[String]) -> StrSynthResult {
    let body = code_s(&e, params);
    let decls = params
        .iter()
        .map(|p| format!("{p}: string"))
        .collect::<Vec<_>>()
        .join(", ");
    let fn_name = "transform";
    let code = format!("fn {fn_name}({decls}) -> string {{\n    return {body};\n}}\n");
    StrSynthResult {
        success: true,
        code,
        method: "string_synth".to_string(),
        error: None,
    }
}

fn fail(msg: &str) -> StrSynthResult {
    StrSynthResult {
        success: false,
        code: String::new(),
        method: "string_synth_unsupported".to_string(),
        error: Some(msg.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ex(inputs: &[&str], expected: &str) -> StrSynthExample {
        StrSynthExample {
            inputs: inputs.iter().map(|s| s.to_string()).collect(),
            expected: expected.to_string(),
        }
    }

    fn solve(params: &[&str], exs: &[StrSynthExample]) -> StrSynthResult {
        synthesize_string_program(
            &params.iter().map(|s| s.to_string()).collect::<Vec<_>>(),
            exs,
        )
    }

    #[test]
    fn learns_reverse() {
        let r = solve(
            &["s"],
            &[
                ex(&["abc"], "cba"),
                ex(&["hello"], "olleh"),
                ex(&["xy"], "yx"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
        assert!(r.code.contains("reverse"), "{}", r.code);
    }

    #[test]
    fn learns_capitalize() {
        // first char upper, rest unchanged: cat -> Cat
        let r = solve(
            &["s"],
            &[
                ex(&["cat"], "Cat"),
                ex(&["dog"], "Dog"),
                ex(&["fox"], "Fox"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn learns_full_name_concat() {
        // first + " " + last
        let r = solve(
            &["a", "b"],
            &[
                ex(&["john", "smith"], "john smith"),
                ex(&["jane", "doe"], "jane doe"),
                ex(&["amy", "lee"], "amy lee"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn learns_initials() {
        // first letter of each, uppercased: john smith -> JS
        let r = solve(
            &["a", "b"],
            &[
                ex(&["john", "smith"], "JS"),
                ex(&["jane", "doe"], "JD"),
                ex(&["amy", "lee"], "AL"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn learns_upper() {
        let r = solve(&["s"], &[ex(&["abc"], "ABC"), ex(&["heLLo"], "HELLO")]);
        assert!(r.success, "{:?}", r.error);
        assert!(r.code.contains("upper"));
    }

    #[test]
    fn learns_last_first_with_infix_separator() {
        // last, first — needs the internal ", " separator (an infix literal).
        let r = solve(
            &["a", "b"],
            &[
                ex(&["john", "smith"], "smith, john"),
                ex(&["jane", "doe"], "doe, jane"),
                ex(&["amy", "lee"], "lee, amy"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn learns_email_template() {
        // a + "@" + b + ".com"; "co" appears inside ".com", testing segmentation robustness.
        let r = solve(
            &["a", "b"],
            &[
                ex(&["john", "acme"], "john@acme.com"),
                ex(&["amy", "x"], "amy@x.com"),
                ex(&["bob", "co"], "bob@co.com"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
        assert!(
            r.code.contains("@") && r.code.contains(".com"),
            "{}",
            r.code
        );
    }

    #[test]
    fn learns_split_take_domain() {
        // domain after @, with VARYING local-part lengths (slice can't do it).
        let r = solve(
            &["s"],
            &[
                ex(&["john@acme.com"], "acme.com"),
                ex(&["a@x.org"], "x.org"),
                ex(&["robert@longname.net"], "longname.net"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
        assert!(r.code.contains("split"), "{}", r.code);
    }

    #[test]
    fn learns_first_word() {
        let r = solve(
            &["s"],
            &[
                ex(&["hello world"], "hello"),
                ex(&["a b c"], "a"),
                ex(&["one two"], "one"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn declines_when_unseparable() {
        // Same input mapped to two different outputs — no function can fit.
        let r = solve(&["s"], &[ex(&["x"], "a"), ex(&["x"], "b")]);
        assert!(!r.success);
    }
}
