//! General string-program synthesizer.
//!
//! Makes nSynth fully capable of string-driven programs: given input→output
//! string examples (1+ string args), it bottom-up enumerates a string-expression
//! grammar and returns a verified Mog program. This is the string analog of the
//! scalar enumerative synthesizer — FlashFill-style, deduped by evaluation
//! signature — and covers reverse, case transforms, slicing, affixing, literal
//! replacement, field concatenation, initials, and their compositions.
//!
//! Output strings live entirely in this additive path (the numeric `Example`
//! pipeline is untouched); `morph_transduce` is the fast specialist for
//! suffix-conditioned morphology, this is the general fallback.

use std::collections::HashSet;

#[derive(Clone, Debug)]
pub struct StrSynthExample {
    pub inputs: Vec<String>,
    pub expected: String,
}

#[derive(Clone, Debug)]
pub struct StrSynthResult {
    pub success: bool,
    pub code: String,
    pub method: String,
    pub error: Option<String>,
}

// ── Expression grammar ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash)]
enum IExpr {
    Const(i64),
    Len(Box<SExpr>, i64), // E.len - k  (k >= 0; k == 0 is E.len)
}

#[derive(Clone, PartialEq, Eq, Hash)]
enum SExpr {
    Var(usize),
    Lit(String),
    Upper(Box<SExpr>),
    Lower(Box<SExpr>),
    Trim(Box<SExpr>),
    Reverse(Box<SExpr>),
    Concat(Box<SExpr>, Box<SExpr>),
    Slice(Box<SExpr>, IExpr, IExpr),
    Replace(Box<SExpr>, String, String),
    Split(Box<SExpr>, String, usize), // E.split(sep)[k]
}

fn clamp(i: i64, n: usize) -> usize {
    if i < 0 {
        0
    } else if i as usize > n {
        n
    } else {
        i as usize
    }
}

fn eval_i(e: &IExpr, inputs: &[String]) -> Option<i64> {
    match e {
        IExpr::Const(k) => Some(*k),
        IExpr::Len(base, k) => {
            let s = eval_s(base, inputs)?;
            Some(s.chars().count() as i64 - *k)
        }
    }
}

fn eval_s(e: &SExpr, inputs: &[String]) -> Option<String> {
    Some(match e {
        SExpr::Var(i) => inputs.get(*i)?.clone(),
        SExpr::Lit(s) => s.clone(),
        SExpr::Upper(a) => eval_s(a, inputs)?.to_uppercase(),
        SExpr::Lower(a) => eval_s(a, inputs)?.to_lowercase(),
        SExpr::Trim(a) => eval_s(a, inputs)?.trim().to_string(),
        SExpr::Reverse(a) => eval_s(a, inputs)?.chars().rev().collect(),
        SExpr::Concat(a, b) => eval_s(a, inputs)? + &eval_s(b, inputs)?,
        SExpr::Slice(a, lo, hi) => {
            let s = eval_s(a, inputs)?;
            let chars: Vec<char> = s.chars().collect();
            let lo = clamp(eval_i(lo, inputs)?, chars.len());
            let hi = clamp(eval_i(hi, inputs)?, chars.len());
            if lo >= hi {
                String::new()
            } else {
                chars[lo..hi].iter().collect()
            }
        }
        SExpr::Replace(a, old, new) => {
            if old.is_empty() {
                return None;
            }
            eval_s(a, inputs)?.replace(old, new)
        }
        SExpr::Split(a, sep, k) => {
            if sep.is_empty() {
                return None;
            }
            let s = eval_s(a, inputs)?;
            s.split(sep.as_str()).nth(*k)?.to_string()
        }
    })
}

// ── Reflective mining surface (NL-BRIDGE-2-AUTO-MINER) ───────────────────────
//
// The capability AUTO-MINER reflects the engine's OWN synthesizable string-op
// surface — the unary `SExpr` variants this synthesizer can actually PRODUCE —
// into capability descriptors, rather than re-typing a phrase->op list. The op
// set is derived FROM the `SExpr` enum here (one arm per unary variant); each
// descriptor's `example_cases` are AUTO-GENERATED by RUNNING the real `eval_s`
// on canonical inputs (the same auto-run trick as `teacher_examples_from_code`
// in differentiable.rs:249), and its codegen comes from the real `code_s`. So
// the mined vocabulary is provably DERIVED from + EQUAL to the engine symbol
// table: adding a unary variant to `SExpr` + re-running the miner makes it
// appear with no hand edit, and the `mineable_string_ops_exhaustive` guard in
// this module fails closed if a new variant is left unmapped.

/// A single mined string-op capability: a unary `string -> string` operation
/// the synthesizer can produce, with its canonical name and a closure onto the
/// REAL `eval_s` of the variant so callers manufacture example_cases by running
/// it (never by hand).
pub struct MinedStringOp {
    /// Canonical lemma for the registry (also the engine surface name).
    pub lemma: &'static str,
    /// The Mog code template `code_s` emits for this op (over param `s`), e.g.
    /// `s.lower()`. Derived from the real codegen, not hand-written.
    pub code_body: String,
    /// Run the op on an input string via the REAL `eval_s`. `None` only if the
    /// underlying `eval_s` returns `None` (it never does for these total ops).
    pub run: fn(&str) -> Option<String>,
}

// Each closure delegates to the REAL `eval_s` over the variant rooted at Var(0),
// so example_cases are manufactured by the production evaluator, not a re-impl.
fn run_upper(s: &str) -> Option<String> {
    eval_s(&SExpr::Upper(Box::new(SExpr::Var(0))), &[s.to_string()])
}
fn run_lower(s: &str) -> Option<String> {
    eval_s(&SExpr::Lower(Box::new(SExpr::Var(0))), &[s.to_string()])
}
fn run_trim(s: &str) -> Option<String> {
    eval_s(&SExpr::Trim(Box::new(SExpr::Var(0))), &[s.to_string()])
}
fn run_reverse(s: &str) -> Option<String> {
    eval_s(&SExpr::Reverse(Box::new(SExpr::Var(0))), &[s.to_string()])
}

/// Enumerate the engine's synthesizable UNARY `string -> string` ops by
/// reflecting the `SExpr` enum. The `match` over a freshly-constructed sample of
/// every variant is the emergence anchor: it is EXHAUSTIVE over `SExpr`, so a new
/// variant added to the enum makes this stop compiling until it is classified as
/// a mineable unary op (mapped) or explicitly skipped (n-ary / parameterised /
/// non-unary — e.g. `Concat`, `Slice`, `Replace`, `Split`, which are not a
/// pure `string -> string` capability over a single arg). The returned ops use
/// the variant's own `code_s` and `eval_s`, so name+behaviour come from the
/// engine, never a hand table.
pub fn mineable_string_ops() -> Vec<MinedStringOp> {
    let var = SExpr::Var(0);
    let params = ["s".to_string()];
    // Build one descriptor per UNARY variant by constructing it over `var` and
    // reading its real `code_s`. Anything not a unary `string->string` op is
    // skipped here (it is not a single-arg capability) but still listed in the
    // exhaustive match below so the enum stays covered.
    let mk = |variant: SExpr, lemma: &'static str, run: fn(&str) -> Option<String>| MinedStringOp {
        lemma,
        code_body: code_s(&variant, &params),
        run,
    };
    vec![
        mk(SExpr::Upper(Box::new(var.clone())), "uppercase", run_upper),
        mk(SExpr::Lower(Box::new(var.clone())), "lowercase", run_lower),
        mk(SExpr::Trim(Box::new(var.clone())), "trim", run_trim),
        mk(
            SExpr::Reverse(Box::new(var.clone())),
            "reverse_string",
            run_reverse,
        ),
    ]
}

/// EMERGENCE GUARD (compile + test enforced): assert the mined op set is exactly
/// the unary `string->string` arm of the `SExpr` enum. The exhaustive `match`
/// fails to compile if a NEW `SExpr` variant is added without a decision here;
/// the runtime assertions confirm the mined lemmas line up with the unary arms,
/// proving the vocabulary is DERIVED from the engine symbol table, not hand-typed.
#[cfg(test)]
pub(crate) fn mineable_string_ops_exhaustive() {
    // Sample one value of every SExpr variant. The match is EXHAUSTIVE: a new
    // variant breaks this until classified, so the mined surface cannot silently
    // drift from the enum.
    let samples: Vec<SExpr> = vec![
        SExpr::Var(0),
        SExpr::Lit(String::new()),
        SExpr::Upper(Box::new(SExpr::Var(0))),
        SExpr::Lower(Box::new(SExpr::Var(0))),
        SExpr::Trim(Box::new(SExpr::Var(0))),
        SExpr::Reverse(Box::new(SExpr::Var(0))),
        SExpr::Concat(Box::new(SExpr::Var(0)), Box::new(SExpr::Var(0))),
        SExpr::Slice(Box::new(SExpr::Var(0)), IExpr::Const(0), IExpr::Const(1)),
        SExpr::Replace(Box::new(SExpr::Var(0)), "a".into(), "b".into()),
        SExpr::Split(Box::new(SExpr::Var(0)), ",".into(), 0),
    ];
    let mined: std::collections::HashSet<&'static str> =
        mineable_string_ops().into_iter().map(|m| m.lemma).collect();
    for s in &samples {
        // Exhaustive over SExpr — adding a variant forces a new arm.
        let is_mineable_unary = match s {
            SExpr::Upper(_) | SExpr::Lower(_) | SExpr::Trim(_) | SExpr::Reverse(_) => true,
            // Not a unary single-arg string->string capability — intentionally
            // not mined (n-ary / literal / parameterised).
            SExpr::Var(_)
            | SExpr::Lit(_)
            | SExpr::Concat(_, _)
            | SExpr::Slice(_, _, _)
            | SExpr::Replace(_, _, _)
            | SExpr::Split(_, _, _) => false,
        };
        // Every mineable-unary variant MUST be present in the mined set; every
        // non-mineable variant MUST be absent — the mined surface == the unary arm.
        let lemma_for = |s: &SExpr| -> Option<&'static str> {
            match s {
                SExpr::Upper(_) => Some("uppercase"),
                SExpr::Lower(_) => Some("lowercase"),
                SExpr::Trim(_) => Some("trim"),
                SExpr::Reverse(_) => Some("reverse_string"),
                _ => None,
            }
        };
        match (is_mineable_unary, lemma_for(s)) {
            (true, Some(l)) => assert!(
                mined.contains(l),
                "unary SExpr variant {l} missing from mined surface"
            ),
            (true, None) => panic!("mineable unary variant has no lemma mapping"),
            (false, _) => { /* not mined; ok */ }
        }
    }
    // No EXTRA lemmas beyond the unary arm.
    assert_eq!(mined.len(), 4, "mined string surface drifted from SExpr enum");
}

// ── Codegen to Mog ───────────────────────────────────────────────────────────

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn code_i(e: &IExpr, params: &[String]) -> String {
    match e {
        IExpr::Const(k) => k.to_string(),
        IExpr::Len(base, 0) => format!("{}.len", code_s(base, params)),
        IExpr::Len(base, k) => format!("{}.len - {k}", code_s(base, params)),
    }
}

fn code_s(e: &SExpr, params: &[String]) -> String {
    match e {
        SExpr::Var(i) => params[*i].clone(),
        SExpr::Lit(s) => format!("\"{}\"", esc(s)),
        SExpr::Upper(a) => format!("{}.upper()", code_s(a, params)),
        SExpr::Lower(a) => format!("{}.lower()", code_s(a, params)),
        SExpr::Trim(a) => format!("{}.trim()", code_s(a, params)),
        SExpr::Reverse(a) => format!("{}.reverse()", code_s(a, params)),
        SExpr::Concat(a, b) => format!("({} + {})", code_s(a, params), code_s(b, params)),
        SExpr::Slice(a, lo, hi) => format!(
            "{}.slice({}, {})",
            code_s(a, params),
            code_i(lo, params),
            code_i(hi, params)
        ),
        SExpr::Replace(a, old, new) => {
            format!(
                "{}.replace(\"{}\", \"{}\")",
                code_s(a, params),
                esc(old),
                esc(new)
            )
        }
        SExpr::Split(a, sep, k) => {
            format!("{}.split(\"{}\")[{k}]", code_s(a, params), esc(sep))
        }
    }
}

// ── Synthesis (bottom-up enumeration, deduped by signature) ──────────────────

/// Evaluate an expression on every example's inputs; None if any eval fails.
fn signature(e: &SExpr, examples: &[StrSynthExample]) -> Option<Vec<String>> {
    examples.iter().map(|ex| eval_s(e, &ex.inputs)).collect()
}

/// Mine literal fragments from the outputs (and a few common separators).
fn mined_literals(examples: &[StrSynthExample]) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::new();
    for sep in [" ", "_", "-", ".", ",", "", "/", ":"] {
        set.insert(sep.to_string());
    }
    for ex in examples {
        let chars: Vec<char> = ex.expected.chars().collect();
        // prefixes/suffixes up to len 4
        for len in 1..=4usize.min(chars.len()) {
            set.insert(chars[..len].iter().collect());
            set.insert(chars[chars.len() - len..].iter().collect());
        }
        // short infix substrings (len <= 3) — captures internal separators like ", "
        for start in 0..chars.len() {
            for len in 1..=3usize.min(chars.len() - start) {
                set.insert(chars[start..start + len].iter().collect());
            }
        }
    }
    let mut v: Vec<String> = set.into_iter().collect();
    v.sort();
    v
}

/// Delimiter characters for split: common separators plus any non-alphanumeric
/// character that occurs in the inputs.
fn mined_delimiters(examples: &[StrSynthExample]) -> Vec<String> {
    let mut set: HashSet<String> = HashSet::new();
    for d in [" ", "@", ".", ",", "-", "_", "/", ":", "|"] {
        set.insert(d.to_string());
    }
    for ex in examples {
        for inp in &ex.inputs {
            for c in inp.chars() {
                if !c.is_alphanumeric() {
                    set.insert(c.to_string());
                }
            }
        }
    }
    let mut v: Vec<String> = set.into_iter().collect();
    v.sort();
    v
}

/// A transform applied to an input value when it appears in the output.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Xf {
    Id,
    Upper,
    Lower,
    Cap, // first char upper, rest unchanged
}

fn apply_xf(x: Xf, s: &str) -> String {
    match x {
        Xf::Id => s.to_string(),
        Xf::Upper => s.to_uppercase(),
        Xf::Lower => s.to_lowercase(),
        Xf::Cap => {
            let mut c = s.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        }
    }
}

#[derive(Clone, PartialEq, Eq)]
enum Seg {
    Const(String),
    Var(usize, Xf),
}

fn xf_to_sexpr(i: usize, x: Xf) -> SExpr {
    let v = Box::new(SExpr::Var(i));
    match x {
        Xf::Id => SExpr::Var(i),
        Xf::Upper => SExpr::Upper(v),
        Xf::Lower => SExpr::Lower(v),
        Xf::Cap => SExpr::Concat(
            Box::new(SExpr::Upper(Box::new(SExpr::Slice(
                Box::new(SExpr::Var(i)),
                IExpr::Const(0),
                IExpr::Const(1),
            )))),
            Box::new(SExpr::Slice(
                Box::new(SExpr::Var(i)),
                IExpr::Const(1),
                IExpr::Len(Box::new(SExpr::Var(i)), 0),
            )),
        ),
    }
}

/// Greedy left-to-right segmentation of `output` into input-derived pieces and
/// constants. At each position prefer the longest input-transform match.
fn segment(output: &str, inputs: &[String]) -> Option<Vec<Seg>> {
    let chars: Vec<char> = output.chars().collect();
    let mut segs: Vec<Seg> = Vec::new();
    let mut cur_const = String::new();
    let mut pos = 0;
    while pos < chars.len() {
        let rest: String = chars[pos..].iter().collect();
        let mut best: Option<(usize, usize, Xf)> = None; // (len_chars, input_idx, xf)
        for (i, v) in inputs.iter().enumerate() {
            if v.is_empty() {
                continue;
            }
            for x in [Xf::Id, Xf::Upper, Xf::Lower, Xf::Cap] {
                let t = apply_xf(x, v);
                if !t.is_empty() && rest.starts_with(&t) {
                    let l = t.chars().count();
                    if best.map(|(bl, _, _)| l > bl).unwrap_or(true) {
                        best = Some((l, i, x));
                    }
                }
            }
        }
        if let Some((l, i, x)) = best {
            if !cur_const.is_empty() {
                segs.push(Seg::Const(std::mem::take(&mut cur_const)));
            }
            segs.push(Seg::Var(i, x));
            pos += l;
        } else {
            cur_const.push(chars[pos]);
            pos += 1;
        }
    }
    if !cur_const.is_empty() {
        segs.push(Seg::Const(cur_const));
    }
    Some(segs)
}

fn skeleton_to_sexpr(sk: Vec<Seg>) -> Option<SExpr> {
    let mut it = sk.into_iter().rev();
    let mut acc = match it.next()? {
        Seg::Const(s) => SExpr::Lit(s),
        Seg::Var(i, x) => xf_to_sexpr(i, x),
    };
    for seg in it {
        let left = match seg {
            Seg::Const(s) => SExpr::Lit(s),
            Seg::Var(i, x) => xf_to_sexpr(i, x),
        };
        acc = SExpr::Concat(Box::new(left), Box::new(acc));
    }
    Some(acc)
}

/// FlashFill-style template synthesis. Greedy segmentation can mis-fire when an
/// input value coincidentally appears inside a constant region (e.g. "co" inside
/// ".com"), so we treat EACH example's segmentation as a candidate template and
/// keep the first whose program reproduces every example's output.
fn try_template(examples: &[StrSynthExample]) -> Option<SExpr> {
    let target: Vec<&str> = examples.iter().map(|e| e.expected.as_str()).collect();
    for ex in examples {
        let segs = match segment(&ex.expected, &ex.inputs) {
            Some(s) => s,
            None => continue,
        };
        if !segs.iter().any(|s| matches!(s, Seg::Var(_, _))) {
            continue;
        }
        let Some(e) = skeleton_to_sexpr(segs) else {
            continue;
        };
        let ok = examples
            .iter()
            .zip(&target)
            .all(|(ex, want)| eval_s(&e, &ex.inputs).as_deref() == Some(*want));
        if ok {
            return Some(e);
        }
    }
    None
}

pub fn synthesize_string_program(
    params: &[String],
    examples: &[StrSynthExample],
) -> StrSynthResult {
    const MAX_SIZE: usize = 7;
    const MAX_BANK: usize = 40_000;
    let n_args = params.len();
    if examples.is_empty() || n_args == 0 {
        return fail("no examples / no args");
    }

    // COOPERATIVE WALL-CLOCK DEADLINE. The MAX_SIZE/MAX_BANK bounds cap the search
    // *space* but not its *time*: on a large mostly-constant lexicon (e.g. an
    // irregular-inflection map where 30+ inputs share one long sentinel output and
    // a handful differ), the size-ordered Concat product `by_size[left] x
    // by_size[right]` with a 40k-per-size bank, each candidate re-evaluated over
    // every example by `signature`, can run for many minutes before exhausting the
    // bound. That is what hung the comprehension base build (irregular_3sg /
    // irregular_past). The bound reused here is the solver's existing enumerative
    // budget (`NSYNTH_ENUM_BUDGET_MS`, default 18s) — the SAME cooperative deadline
    // `self_extend` shrinks to bound a teach. On deadline we stop enumerating and
    // return a MISS (`fail`), which is sound: this function only ever returns a
    // signature-verified program or a failure, so an early failure can never emit a
    // wrong program — the caller (the string-output pipeline) then falls through to
    // the verified whole-word lexicon path, which memorizes the map exactly.
    let deadline = {
        let budget_ms: u64 = std::env::var("NSYNTH_ENUM_BUDGET_MS")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(18_000);
        std::time::Instant::now() + std::time::Duration::from_millis(budget_ms)
    };

    let target: Vec<String> = examples.iter().map(|e| e.expected.clone()).collect();

    // Fast structural pre-pass: concatenation templates (const + input + const ...).
    if let Some(e) = try_template(examples) {
        if signature(&e, examples).as_ref() == Some(&target) {
            return emit(e, params);
        }
    }
    let lits = mined_literals(examples);
    let dels = mined_delimiters(examples);
    let ixs: Vec<IExpr> = {
        let mut ix = vec![
            IExpr::Const(0),
            IExpr::Const(1),
            IExpr::Const(2),
            IExpr::Const(3),
        ];
        for i in 0..n_args {
            for k in 0..=2 {
                ix.push(IExpr::Len(Box::new(SExpr::Var(i)), k));
            }
        }
        ix
    };

    // Size-ordered bottom-up enumeration, deduped by evaluation signature. by_size[k]
    // holds the distinct expressions of size k; we always find the smallest program.
    let mut seen: HashSet<Vec<String>> = HashSet::new();
    let mut by_size: Vec<Vec<(SExpr, Vec<String>)>> = vec![Vec::new(); MAX_SIZE + 1];

    macro_rules! try_push {
        ($e:expr, $size:expr) => {{
            let e = $e;
            if let Some(sig) = signature(&e, examples) {
                if sig == target {
                    return emit(e, params);
                }
                if seen.insert(sig.clone()) {
                    by_size[$size].push((e, sig));
                }
            }
        }};
    }

    // Size 1: variables + literals.
    for i in 0..n_args {
        try_push!(SExpr::Var(i), 1);
    }
    for l in &lits {
        try_push!(SExpr::Lit(l.clone()), 1);
    }

    for size in 2..=MAX_SIZE {
        if std::time::Instant::now() >= deadline {
            return fail("string enumeration deadline exceeded");
        }
        // 1. Concat first (field assembly) — the most useful op; never starve it.
        for left in 1..size {
            let right = size - 1 - left;
            if right < 1 {
                continue;
            }
            let las: Vec<SExpr> = by_size[left].iter().map(|(e, _)| e.clone()).collect();
            let ras: Vec<SExpr> = by_size[right].iter().map(|(e, _)| e.clone()).collect();
            for a in &las {
                // The Concat product is the explosive inner loop; check the deadline
                // once per `a` so a runaway pairing aborts within ~one row, not after
                // the whole product.
                if std::time::Instant::now() >= deadline {
                    return fail("string enumeration deadline exceeded");
                }
                for b in &ras {
                    try_push!(
                        SExpr::Concat(Box::new(a.clone()), Box::new(b.clone())),
                        size
                    );
                }
            }
        }
        // 2. Unary case/reverse/trim over size-1 children.
        let children: Vec<SExpr> = by_size[size - 1].iter().map(|(e, _)| e.clone()).collect();
        for e in &children {
            try_push!(SExpr::Upper(Box::new(e.clone())), size);
            try_push!(SExpr::Lower(Box::new(e.clone())), size);
            try_push!(SExpr::Trim(Box::new(e.clone())), size);
            try_push!(SExpr::Reverse(Box::new(e.clone())), size);
        }
        // 3. Slices + split-take over size-1 children.
        for e in &children {
            for lo in &ixs {
                for hi in &ixs {
                    try_push!(
                        SExpr::Slice(Box::new(e.clone()), lo.clone(), hi.clone()),
                        size
                    );
                }
            }
            for sep in &dels {
                for k in 0..3 {
                    try_push!(SExpr::Split(Box::new(e.clone()), sep.clone(), k), size);
                }
            }
            if by_size[size].len() > MAX_BANK {
                break;
            }
        }
        // 4. Replace — only directly on variables, with mined non-separator
        //    literals, since it is the most combinatorially explosive op.
        if size == 2 {
            for i in 0..n_args {
                for old in &lits {
                    if old.chars().count() < 2 {
                        continue;
                    }
                    for new in &lits {
                        try_push!(
                            SExpr::Replace(Box::new(SExpr::Var(i)), old.clone(), new.clone()),
                            size
                        );
                    }
                }
            }
        }
    }

    if std::env::var("STRSYNTH_DEBUG").is_ok() {
        let sizes: Vec<usize> = by_size.iter().map(|v| v.len()).collect();
        eprintln!(
            "[strsynth] by_size lens = {sizes:?}; lits={}; target={target:?}",
            lits.len()
        );
    }
    fail("no string program found within the enumeration bound")
}

fn emit(e: SExpr, params: &[String]) -> StrSynthResult {
    let body = code_s(&e, params);
    let decls = params
        .iter()
        .map(|p| format!("{p}: string"))
        .collect::<Vec<_>>()
        .join(", ");
    let fn_name = "transform";
    let code = format!("fn {fn_name}({decls}) -> string {{\n    return {body};\n}}\n");
    StrSynthResult {
        success: true,
        code,
        method: "string_synth".to_string(),
        error: None,
    }
}

fn fail(msg: &str) -> StrSynthResult {
    StrSynthResult {
        success: false,
        code: String::new(),
        method: "string_synth_unsupported".to_string(),
        error: Some(msg.to_string()),
    }
}

// ── C1: word-list composition (statement-level, loop-emitting) ───────────────
//
// The `SExpr` grammar above emits a single INLINE EXPRESSION, so it cannot express
// a transform that MAPS over the words of a string (split -> per-word op -> join)
// or reorders the word LIST — those need a loop / list method, i.e. statements.
// This closes part of the string-list gap (string 20.7% vs int 69%): title-case,
// reverse-each-word, sort-words, reverse-word-order. The search is tiny
// (separators x shapes) and EVERY candidate is self-verified against the examples
// through the real interpreter before it is returned, so a wrong shape or a bad
// emit can never be a false accept — never-wrong by construction.

#[derive(Clone, Copy)]
enum WordShape {
    /// Uppercase the first char of each word, rest unchanged (matches the emit).
    TitleCase,
    /// Reverse the characters of each word in place.
    ReverseEachWord,
    /// Sort the words ascending (lexicographic), rejoin.
    SortWords,
    /// Reverse the ORDER of the words, rejoin.
    ReverseWordOrder,
    /// The single longest word (first on a length tie).
    LongestWord,
    /// The single shortest word (first on a length tie).
    ShortestWord,
    /// First character of each word, concatenated (initials): "hi there" -> "ht".
    Initials,
}

impl WordShape {
    fn name(self) -> &'static str {
        match self {
            WordShape::TitleCase => "title_case",
            WordShape::ReverseEachWord => "reverse_each_word",
            WordShape::SortWords => "sort_words",
            WordShape::ReverseWordOrder => "reverse_word_order",
            WordShape::LongestWord => "longest_word",
            WordShape::ShortestWord => "shortest_word",
            WordShape::Initials => "initials",
        }
    }
}

/// First char uppercased, rest verbatim — matches the emitted Mog
/// (`w.slice(0,1).upper() + w.slice(1, w.len)`), NOT a lowercasing title-case.
fn cap_first(w: &str) -> String {
    let mut c = w.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

/// Apply a word shape in RUST, mirroring the emitted Mog exactly (so the predicted
/// output the search matches on equals what the program will compute).
fn apply_word_shape(input: &str, sep: &str, shape: WordShape) -> String {
    let words: Vec<&str> = input.split(sep).collect();
    match shape {
        WordShape::TitleCase => {
            words.iter().map(|w| cap_first(w)).collect::<Vec<_>>().join(sep)
        }
        WordShape::ReverseEachWord => words
            .iter()
            .map(|w| w.chars().rev().collect::<String>())
            .collect::<Vec<_>>()
            .join(sep),
        WordShape::SortWords => {
            let mut ws = words.clone();
            ws.sort_unstable();
            ws.join(sep)
        }
        WordShape::ReverseWordOrder => {
            let mut ws = words.clone();
            ws.reverse();
            ws.join(sep)
        }
        // First on a length tie, char-counted (matches Mog `.len` = char count and
        // the strict `>`/`<` emit that only replaces on a STRICT win).
        WordShape::LongestWord => {
            let mut best = *words.first().unwrap_or(&"");
            for w in words.iter().skip(1) {
                if w.chars().count() > best.chars().count() {
                    best = w;
                }
            }
            best.to_string()
        }
        WordShape::ShortestWord => {
            let mut best = *words.first().unwrap_or(&"");
            for w in words.iter().skip(1) {
                if w.chars().count() < best.chars().count() {
                    best = w;
                }
            }
            best.to_string()
        }
        // First char of each word, joined with "" (empty word contributes "").
        WordShape::Initials => words
            .iter()
            .map(|w| w.chars().next().map(String::from).unwrap_or_default())
            .collect::<String>(),
    }
}

/// Emit the Mog program for a word shape. `p` is the (single) string parameter,
/// `sep` the separator literal. Entry fn is `transform` so the caller's
/// `replacen("fn transform(", ...)` renames it, matching `synthesize_string_program`.
fn emit_word_program(p: &str, sep: &str, shape: WordShape) -> String {
    let sep = esc(sep);
    match shape {
        WordShape::TitleCase => format!(
            "fn transform({p}: string) -> string {{\n    words: [string] = {p}.split(\"{sep}\");\n    out: [string] = [];\n    i: i64 = 0;\n    while i < words.len {{\n        w: string = words[i];\n        first: string = w.slice(0, 1);\n        rest: string = w.slice(1, w.len);\n        out.push(first.upper() + rest);\n        i = i + 1;\n    }}\n    return out.join(\"{sep}\");\n}}\n"
        ),
        WordShape::ReverseEachWord => format!(
            "fn transform({p}: string) -> string {{\n    words: [string] = {p}.split(\"{sep}\");\n    out: [string] = [];\n    i: i64 = 0;\n    while i < words.len {{\n        out.push(words[i].reverse());\n        i = i + 1;\n    }}\n    return out.join(\"{sep}\");\n}}\n"
        ),
        WordShape::SortWords => format!(
            "fn transform({p}: string) -> string {{\n    return {p}.split(\"{sep}\").sort().join(\"{sep}\");\n}}\n"
        ),
        WordShape::ReverseWordOrder => format!(
            "fn transform({p}: string) -> string {{\n    return {p}.split(\"{sep}\").reverse().join(\"{sep}\");\n}}\n"
        ),
        WordShape::LongestWord => format!(
            "fn transform({p}: string) -> string {{\n    words: [string] = {p}.split(\"{sep}\");\n    best: string = words[0];\n    i: i64 = 1;\n    while i < words.len {{\n        if words[i].len > best.len {{\n            best = words[i];\n        }}\n        i = i + 1;\n    }}\n    return best;\n}}\n"
        ),
        WordShape::ShortestWord => format!(
            "fn transform({p}: string) -> string {{\n    words: [string] = {p}.split(\"{sep}\");\n    best: string = words[0];\n    i: i64 = 1;\n    while i < words.len {{\n        if words[i].len < best.len {{\n            best = words[i];\n        }}\n        i = i + 1;\n    }}\n    return best;\n}}\n"
        ),
        WordShape::Initials => format!(
            "fn transform({p}: string) -> string {{\n    words: [string] = {p}.split(\"{sep}\");\n    out: [string] = [];\n    i: i64 = 0;\n    while i < words.len {{\n        out.push(words[i].slice(0, 1));\n        i = i + 1;\n    }}\n    return out.join(\"\");\n}}\n"
        ),
    }
}

/// Synthesize a word-list composition (title-case / reverse-each-word /
/// sort-words / reverse-word-order) from `string -> string` examples. Returns a
/// SELF-VERIFIED Mog program or None. Never-wrong: a candidate is only returned if
/// it reproduces every example through the real interpreter.
pub fn synthesize_word_program(
    params: &[String],
    examples: &[StrSynthExample],
) -> Option<StrSynthResult> {
    if params.len() != 1 || examples.len() < 2 {
        return None;
    }
    // Single string arg with a string output; skip if any example isn't 1-arg.
    if examples.iter().any(|ex| ex.inputs.len() != 1) {
        return None;
    }
    // A shape that leaves every example unchanged is the identity, not this op.
    if examples.iter().all(|ex| ex.inputs[0] == ex.expected) {
        return None;
    }
    let p = &params[0];
    const SEPS: [&str; 5] = [" ", "-", "_", ",", "/"];
    const SHAPES: [WordShape; 7] = [
        WordShape::TitleCase,
        WordShape::ReverseEachWord,
        WordShape::SortWords,
        WordShape::ReverseWordOrder,
        WordShape::LongestWord,
        WordShape::ShortestWord,
        WordShape::Initials,
    ];
    for sep in SEPS {
        // A word shape only applies to GENUINE multi-word input: at least one
        // example must split into >=2 non-empty words on this separator. Without
        // this, a shape coincidentally matches a single-word transform — e.g.
        // `longest_word` reproduces `trim` ("  hi  " -> "hi", the lone non-empty
        // segment) and would hijack it when this synthesizer runs before the real
        // trim tier.
        let multiword = examples
            .iter()
            .any(|ex| ex.inputs[0].split(sep).filter(|w| !w.is_empty()).count() >= 2);
        if !multiword {
            continue;
        }
        for shape in SHAPES {
            let predicts_all = examples
                .iter()
                .all(|ex| apply_word_shape(&ex.inputs[0], sep, shape) == ex.expected);
            if !predicts_all {
                continue;
            }
            let code = emit_word_program(p, sep, shape);
            // Never-wrong gate: the emitted program must reproduce every example
            // through the real interpreter (catches any emit/semantics drift).
            let bench: Vec<crate::benchmark::Example> = examples
                .iter()
                .map(|ex| crate::benchmark::Example {
                    inputs: vec![crate::benchmark::Value::Str(ex.inputs[0].clone())],
                    expected: crate::benchmark::Value::Str(ex.expected.clone()),
                })
                .collect();
            if crate::runtime::code_reproduces_examples(&code, &bench) {
                return Some(StrSynthResult {
                    success: true,
                    code,
                    method: format!("word-{}", shape.name()),
                    error: None,
                });
            }
        }
    }
    None
}

// ── string -> int aggregations ───────────────────────────────────────────────
//
// A novel `string -> int` task (e.g. "count the words") has no synthesizer today:
// the expression/word grammars produce string outputs, the combinator takes
// int-list input, and only a matching LIBRARY op can catch it. This closes the two
// most common, TRANSPILABLE shapes: char count (`s.len`) and word count
// (`s.split(sep).len`). count-a-specific-char is deliberately NOT included — it
// needs a `for ch in s.chars()` loop that breaks downstream Rust transpilation.

fn verify_str_int(code: &str, examples: &[(String, i64)]) -> bool {
    let bench: Vec<crate::benchmark::Example> = examples
        .iter()
        .map(|(s, o)| crate::benchmark::Example {
            inputs: vec![crate::benchmark::Value::Str(s.clone())],
            expected: crate::benchmark::Value::Int(*o),
        })
        .collect();
    crate::runtime::code_reproduces_examples(code, &bench)
}

/// Synthesize a `string -> int` aggregation (char count / word count) from single
/// string-arg examples. Returns a SELF-VERIFIED Mog program or None. Never-wrong: a
/// candidate is only returned if it reproduces every example via the interpreter.
pub fn synthesize_string_int_program(
    params: &[String],
    examples: &[(String, i64)],
) -> Option<StrSynthResult> {
    if params.len() != 1 || examples.len() < 2 {
        return None;
    }
    let p = &params[0];
    // Char count: s.len (Mog `.len` is char count).
    if examples.iter().all(|(s, o)| s.chars().count() as i64 == *o) {
        let code = format!("fn transform({p}: string) -> i64 {{\n    return {p}.len;\n}}\n");
        if verify_str_int(&code, examples) {
            return Some(StrSynthResult {
                success: true,
                code,
                method: "str-char_count".to_string(),
                error: None,
            });
        }
    }
    // Word count: s.split(sep).len. Require some example to actually split into >1
    // segment (else it's the constant 1 or coincides with something trivial).
    for sep in [" ", "-", "_", ",", "/"] {
        let matches = examples.iter().all(|(s, o)| s.split(sep).count() as i64 == *o);
        let nontrivial = examples.iter().any(|(s, _)| s.split(sep).count() >= 2);
        if matches && nontrivial {
            let code = format!(
                "fn transform({p}: string) -> i64 {{\n    return {p}.split(\"{}\").len;\n}}\n",
                esc(sep)
            );
            if verify_str_int(&code, examples) {
                return Some(StrSynthResult {
                    success: true,
                    code,
                    method: "str-word_count".to_string(),
                    error: None,
                });
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ex(inputs: &[&str], expected: &str) -> StrSynthExample {
        StrSynthExample {
            inputs: inputs.iter().map(|s| s.to_string()).collect(),
            expected: expected.to_string(),
        }
    }

    fn solve(params: &[&str], exs: &[StrSynthExample]) -> StrSynthResult {
        synthesize_string_program(
            &params.iter().map(|s| s.to_string()).collect::<Vec<_>>(),
            exs,
        )
    }

    fn wex(i: &str, o: &str) -> StrSynthExample {
        StrSynthExample { inputs: vec![i.to_string()], expected: o.to_string() }
    }

    /// C1: each word shape synthesizes a SELF-VERIFIED program with the right method.
    /// (A shape only returns if its emitted Mog reproduces every example through the
    /// real interpreter, so these also prove the emits actually run.)
    #[test]
    fn word_program_synthesizes_title_case() {
        let p = vec!["s".to_string()];
        let r = synthesize_word_program(
            &p,
            &[wex("hello world", "Hello World"), wex("one two three", "One Two Three")],
        );
        assert_eq!(r.map(|r| r.method), Some("word-title_case".to_string()));
    }

    #[test]
    fn word_program_synthesizes_reverse_each_word() {
        let p = vec!["s".to_string()];
        let r = synthesize_word_program(&p, &[wex("abc def", "cba fed"), wex("hi bye", "ih eyb")]);
        assert_eq!(r.map(|r| r.method), Some("word-reverse_each_word".to_string()));
    }

    #[test]
    fn word_program_synthesizes_sort_words() {
        let p = vec!["s".to_string()];
        let r = synthesize_word_program(
            &p,
            &[wex("banana apple cherry", "apple banana cherry"), wex("dog cat", "cat dog")],
        );
        assert_eq!(r.map(|r| r.method), Some("word-sort_words".to_string()));
    }

    #[test]
    fn word_program_synthesizes_reverse_word_order() {
        let p = vec!["s".to_string()];
        let r = synthesize_word_program(&p, &[wex("a b c", "c b a"), wex("one two", "two one")]);
        assert_eq!(r.map(|r| r.method), Some("word-reverse_word_order".to_string()));
    }

    #[test]
    fn word_program_synthesizes_longest_word() {
        let p = vec!["s".to_string()];
        // "quick"/"brown" tie at 5 -> first ("quick"), disambiguating longest from last.
        let r = synthesize_word_program(
            &p,
            &[wex("the quick brown fox", "quick"), wex("a bb ccc", "ccc")],
        );
        assert_eq!(r.map(|r| r.method), Some("word-longest_word".to_string()));
    }

    #[test]
    fn word_program_synthesizes_shortest_word() {
        let p = vec!["s".to_string()];
        let r = synthesize_word_program(&p, &[wex("aaa bb c", "c"), wex("hello hi", "hi")]);
        assert_eq!(r.map(|r| r.method), Some("word-shortest_word".to_string()));
    }

    #[test]
    fn word_program_synthesizes_initials() {
        let p = vec!["s".to_string()];
        let r = synthesize_word_program(
            &p,
            &[wex("hello world", "hw"), wex("the quick brown", "tqb"), wex("a b c", "abc")],
        );
        assert_eq!(r.map(|r| r.method), Some("word-initials".to_string()));
    }

    /// Reachability probe: is longest-word solved by THIS synthesizer, or shadowed
    /// by an earlier tier? Asserts the method so we know whether C1 is load-bearing.
    #[test]
    fn solve_problem_longest_word_method() {
        use crate::benchmark::{Example, Problem, Value};
        let ex = |i: &str, o: &str| Example {
            inputs: vec![Value::Str(i.to_string())],
            expected: Value::Str(o.to_string()),
        };
        let problem = Problem {
            name: "longest".to_string(),
            signature: "fn longest(s: string) -> string",
            examples: vec![
                ex("hello world", "hello"),
                ex("the quick brown fox", "quick"),
                ex("one two three", "three"),
                ex("a bb ccc", "ccc"),
                ex("alpha beta", "alpha"),
                ex("x yy zzz", "zzz"),
            ],
            ..Default::default()
        };
        let r = crate::solver::solve_problem(&problem);
        assert!(r.success, "longest word should solve");
        // C1 is LOAD-BEARING here: no other tier computes max-length-word, so this
        // must be the word-list synthesizer (guards against silent shadowing).
        assert!(
            r.method.starts_with("word-"),
            "longest word must solve via the word-list synthesizer, got {}",
            r.method
        );
        assert!(
            crate::runtime::code_reproduces_examples(&r.code, &[ex("i am here now", "here")]),
            "must generalise; method={}",
            r.method
        );
    }

    /// Never-wrong: an example set no word shape reproduces returns None (no guess).
    #[test]
    fn word_program_refuses_unmatched() {
        let p = vec!["s".to_string()];
        let r = synthesize_word_program(&p, &[wex("hello", "olleh"), wex("world", "xyz")]);
        assert!(r.is_none());
    }

    #[test]
    fn string_int_synthesizes_word_count() {
        let p = vec!["s".to_string()];
        let r = synthesize_string_int_program(
            &p,
            &[("hello world".into(), 2), ("one two three".into(), 3), ("a".into(), 1)],
        );
        assert_eq!(r.map(|r| r.method), Some("str-word_count".to_string()));
    }

    #[test]
    fn string_int_synthesizes_char_count() {
        let p = vec!["s".to_string()];
        let r = synthesize_string_int_program(
            &p,
            &[("hello".into(), 5), ("hi".into(), 2), ("abcd".into(), 4)],
        );
        assert_eq!(r.map(|r| r.method), Some("str-char_count".to_string()));
    }

    #[test]
    fn string_int_refuses_unmatched() {
        let p = vec!["s".to_string()];
        let r = synthesize_string_int_program(&p, &[("hello".into(), 99), ("hi".into(), 1)]);
        assert!(r.is_none());
    }

    /// END-TO-END: word-count solves through the real `solve_problem` pipeline via
    /// the new string->int tier (no other tier synthesizes novel string->int).
    #[test]
    fn solve_problem_word_count_end_to_end() {
        use crate::benchmark::{Example, Problem, Value};
        let ex = |i: &str, o: i64| Example {
            inputs: vec![Value::Str(i.to_string())],
            expected: Value::Int(o),
        };
        let problem = Problem {
            name: "wc".to_string(),
            signature: "fn wc(s: string) -> i64",
            examples: vec![
                ex("hello world", 2),
                ex("one two three", 3),
                ex("a b c d", 4),
                ex("single", 1),
                ex("two words", 2),
            ],
            ..Default::default()
        };
        let r = crate::solver::solve_problem(&problem);
        assert!(r.success, "word count should solve: {:?}", r.error);
        assert!(r.method.starts_with("str-"), "via string->int tier, got {}", r.method);
        assert!(crate::runtime::code_reproduces_examples(&r.code, &[ex("a b c d e f", 6)]));
    }

    /// C1 END-TO-END: a title-case task solves through the real `solve_problem`
    /// pipeline (proves the tier is actually REACHED, not just callable in isolation)
    /// and the returned program reproduces a held-out input.
    #[test]
    fn solve_problem_solves_title_case_end_to_end() {
        use crate::benchmark::{Example, Problem, Value};
        let ex = |i: &str, o: &str| Example {
            inputs: vec![Value::Str(i.to_string())],
            expected: Value::Str(o.to_string()),
        };
        let problem = Problem {
            name: "titlecase".to_string(),
            signature: "fn titlecase(s: string) -> string",
            examples: vec![
                ex("hello world", "Hello World"),
                ex("one two three", "One Two Three"),
                ex("foo bar", "Foo Bar"),
                ex("a b c d", "A B C D"),
            ],
            ..Default::default()
        };
        let r = crate::solver::solve_problem(&problem);
        assert!(r.success, "title-case should solve end-to-end: {:?}", r.error);
        assert!(
            crate::runtime::code_reproduces_examples(
                &r.code,
                &[ex("quick brown fox", "Quick Brown Fox")]
            ),
            "solved program must generalise to a held-out sentence; method={}",
            r.method
        );
    }

    #[test]
    fn learns_reverse() {
        let r = solve(
            &["s"],
            &[
                ex(&["abc"], "cba"),
                ex(&["hello"], "olleh"),
                ex(&["xy"], "yx"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
        assert!(r.code.contains("reverse"), "{}", r.code);
    }

    #[test]
    fn learns_capitalize() {
        // first char upper, rest unchanged: cat -> Cat
        let r = solve(
            &["s"],
            &[
                ex(&["cat"], "Cat"),
                ex(&["dog"], "Dog"),
                ex(&["fox"], "Fox"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn learns_full_name_concat() {
        // first + " " + last
        let r = solve(
            &["a", "b"],
            &[
                ex(&["john", "smith"], "john smith"),
                ex(&["jane", "doe"], "jane doe"),
                ex(&["amy", "lee"], "amy lee"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn learns_initials() {
        // first letter of each, uppercased: john smith -> JS
        let r = solve(
            &["a", "b"],
            &[
                ex(&["john", "smith"], "JS"),
                ex(&["jane", "doe"], "JD"),
                ex(&["amy", "lee"], "AL"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn learns_upper() {
        let r = solve(&["s"], &[ex(&["abc"], "ABC"), ex(&["heLLo"], "HELLO")]);
        assert!(r.success, "{:?}", r.error);
        assert!(r.code.contains("upper"));
    }

    #[test]
    fn learns_last_first_with_infix_separator() {
        // last, first — needs the internal ", " separator (an infix literal).
        let r = solve(
            &["a", "b"],
            &[
                ex(&["john", "smith"], "smith, john"),
                ex(&["jane", "doe"], "doe, jane"),
                ex(&["amy", "lee"], "lee, amy"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn learns_email_template() {
        // a + "@" + b + ".com"; "co" appears inside ".com", testing segmentation robustness.
        let r = solve(
            &["a", "b"],
            &[
                ex(&["john", "acme"], "john@acme.com"),
                ex(&["amy", "x"], "amy@x.com"),
                ex(&["bob", "co"], "bob@co.com"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
        assert!(
            r.code.contains("@") && r.code.contains(".com"),
            "{}",
            r.code
        );
    }

    #[test]
    fn learns_split_take_domain() {
        // domain after @, with VARYING local-part lengths (slice can't do it).
        let r = solve(
            &["s"],
            &[
                ex(&["john@acme.com"], "acme.com"),
                ex(&["a@x.org"], "x.org"),
                ex(&["robert@longname.net"], "longname.net"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
        assert!(r.code.contains("split"), "{}", r.code);
    }

    #[test]
    fn learns_first_word() {
        let r = solve(
            &["s"],
            &[
                ex(&["hello world"], "hello"),
                ex(&["a b c"], "a"),
                ex(&["one two"], "one"),
            ],
        );
        assert!(r.success, "{:?}", r.error);
    }

    #[test]
    fn declines_when_unseparable() {
        // Same input mapped to two different outputs — no function can fit.
        let r = solve(&["s"], &[ex(&["x"], "a"), ex(&["x"], "b")]);
        assert!(!r.success);
    }

    /// REGRESSION (UNWALL-4-OPT2-BOUND-BASE-BUILD): a large mostly-constant lexicon
    /// (many inputs sharing one long sentinel output, a few differing) has NO
    /// generalizing string rule, so the enumerator must MISS — and with the
    /// cooperative `NSYNTH_ENUM_BUDGET_MS` deadline it must do so within a BOUNDED
    /// wall-clock time rather than running for the many minutes it took before the
    /// deadline existed. This is the input shape that hung the comprehension base
    /// build (`irregular_3sg` / `irregular_past`). The deadline only ever turns a
    /// would-be (eventual) MISS into a bounded MISS, never a wrong success.
    ///
    /// This test does NOT mutate `NSYNTH_ENUM_BUDGET_MS` (that env is process-global
    /// and would race the other parallel `string_synth` tests); it relies on the
    /// DEFAULT 18s deadline, asserting the miss lands well under the prior hang.
    #[test]
    fn lexicon_map_misses_bounded() {
        // 4 distinct forms + ~30 inputs all mapping to a long sentinel constant.
        let sentinel = "__REGULAR__";
        let mut exs = vec![
            ex(&["be"], "is"),
            ex(&["have"], "has"),
            ex(&["do"], "does"),
            ex(&["go"], "goes"),
        ];
        for w in [
            "walk", "talk", "open", "close", "push", "pull", "read", "write", "send", "show",
            "give", "take", "make", "find", "keep", "hold", "bring", "build", "carry", "offer",
            "hand", "teach", "reach", "watch", "match", "wash", "wish", "rush", "kiss", "miss",
        ] {
            exs.push(ex(&[w], sentinel));
        }
        let t = std::time::Instant::now();
        let r = solve(&["s"], &exs);
        let elapsed = t.elapsed();
        assert!(
            !r.success,
            "an arbitrary lexicon has no generalizing rule — the enumerator must MISS"
        );
        // The default deadline is 18s; assert the miss lands comfortably within it
        // (+slack) — orders of magnitude below the prior multi-minute hang.
        assert!(
            elapsed.as_secs() < 40,
            "enumerator did not give up within the default deadline: {:?}",
            elapsed
        );
    }
}
