//! Code Generation for Probabilistic Programs
//!
//! Template-based code generation for probabilistic programs with sampling

use crate::prob::distribution::ProbDistribution;

/// Generate probabilistic code for a distribution
///
/// Creates executable Rust code with sampling primitives
pub fn generate_probabilistic_code(
    dist: &ProbDistribution,
    params: &[f64],
    fn_name: &str,
) -> String {
    match dist {
        ProbDistribution::Bernoulli { .. } => generate_bernoulli(params, fn_name),
        ProbDistribution::Normal { .. } => generate_normal(params, fn_name),
        ProbDistribution::Categorical { .. } => generate_categorical(params, fn_name),
        ProbDistribution::Poisson { .. } => generate_poisson(params, fn_name),
        ProbDistribution::Uniform { .. } => generate_uniform(params, fn_name),
        _ => format!("// Unsupported distribution for {fn_name}"),
    }
}

/// Generate Bernoulli (coin flip) code
fn generate_bernoulli(params: &[f64], fn_name: &str) -> String {
    let p = if !params.is_empty() { params[0] } else { 0.5 };

    format!(r#"use rand::Rng;

/// Bernoulli sampler with learned bias p = {p:.4}
/// Generated by probabilistic synthesis
fn {fn_name}() -> bool {{
    let p = {p:.4};
    let mut rng = rand::thread_rng();
    let u: f64 = rng.gen();
    u < p
}}
"#)
}

/// Generate Normal (noisy measurement) code
fn generate_normal(params: &[f64], fn_name: &str) -> String {
    let mean = if params.len() > 0 { params[0] } else { 0.0 };
    let std = if params.len() > 1 { params[1] } else { 1.0 };

    format!(r#"use rand::distributions::{{Distribution, Normal}};

/// Normal sampler with learned μ = {mean:.4}, σ = {std:.4}
/// Generated by probabilistic synthesis
fn {fn_name}() -> f64 {{
    let mean = {mean:.4};
    let std = {std:.4};
    let normal = Normal::new(mean, std).unwrap();
    let mut rng = rand::thread_rng();
    normal.sample(&mut rng)
}}
"#)
}

/// Generate Categorical (dice roll) code
fn generate_categorical(params: &[f64], fn_name: &str) -> String {
    let n = params.len();
    let probs_str = params.iter()
        .map(|&p| format!("{:.4}", p))
        .collect::<Vec<_>>()
        .join(", ");

    format!(r#"use rand::Rng;

/// Categorical sampler with learned probabilities [{probs_str}]
/// Generated by probabilistic synthesis
fn {fn_name}() -> i64 {{
    let probs: Vec<f64> = vec![{probs_str}];
    let mut rng = rand::thread_rng();
    let u: f64 = rng.gen();
    let mut cumsum = 0.0;
    for (i, &p) in probs.iter().enumerate() {{
        cumsum += p;
        if u <= cumsum {{
            return i as i64;
        }}
    }}
    ({n} - 1) as i64
}}
"#)
}

/// Generate Poisson (count data) code
fn generate_poisson(params: &[f64], fn_name: &str) -> String {
    let lambda = if !params.is_empty() { params[0] } else { 1.0 };

    format!(r#"use rand::Rng;

/// Poisson sampler with learned λ = {lambda:.4}
/// Generated by probabilistic synthesis
fn {fn_name}() -> i64 {{
    let lambda = {lambda:.4};
    let mut rng = rand::thread_rng();
    let mut l = (-lambda).exp();
    let mut k = 0i64;
    let mut u: f64 = rng.gen();
    while u > l && k < 1000 {{
        k += 1;
        l *= lambda / k as f64;
        u = rng.gen();
    }}
    k
}}
"#)
}

/// Generate Uniform code
fn generate_uniform(params: &[f64], fn_name: &str) -> String {
    let low = if params.len() > 0 { params[0] } else { 0.0 };
    let high = if params.len() > 1 { params[1] } else { 1.0 };

    format!(r#"use rand::Rng;

/// Uniform sampler on [{low:.4}, {high:.4}]
/// Generated by probabilistic synthesis
fn {fn_name}() -> f64 {{
    let low = {low:.4};
    let high = {high:.4};
    let mut rng = rand::thread_rng();
    let u: f64 = rng.gen();
    low + u * (high - low)
}}
"#)
}

/// Generate code for probabilistic function with inputs
pub fn generate_probabilistic_with_inputs(
    dist: &ProbDistribution,
    params: &[f64],
    fn_name: &str,
    param_names: &[String],
) -> String {
    if param_names.is_empty() {
        return generate_probabilistic_code(dist, params, fn_name);
    }

    // For functions with inputs, pass them through
    let params_str = param_names.join(", ");

    match dist {
        ProbDistribution::Bernoulli { .. } => {
            let p = if !params.is_empty() { params[0] } else { 0.5 };
            format!(r#"use rand::Rng;

/// Bernoulli sampler with learned bias p = {p:.4}
fn {fn_name}({params_str}) -> bool {{
    let p = {p:.4};
    let mut rng = rand::thread_rng();
    let u: f64 = rng.gen();
    u < p
}}
"#)
        }
        ProbDistribution::Normal { .. } => {
            let mean = if params.len() > 0 { params[0] } else { 0.0 };
            let std = if params.len() > 1 { params[1] } else { 1.0 };
            format!(r#"use rand::distributions::{{Distribution, Normal}};

/// Normal sampler with learned μ = {mean:.4}, σ = {std:.4}
fn {fn_name}({params_str}) -> f64 {{
    let mean = {mean:.4};
    let std = {std:.4};
    let normal = Normal::new(mean, std).unwrap();
    let mut rng = rand::thread_rng();
    normal.sample(&mut rng)
}}
"#)
        }
        _ => generate_probabilistic_code(dist, params, fn_name),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_bernoulli() {
        let dist = ProbDistribution::Bernoulli { p: 0.7 };
        let code = generate_probabilistic_code(&dist, &[0.7], "coin_flip");
        assert!(code.contains("p = 0.7000"));
        assert!(code.contains("fn coin_flip()"));
        assert!(code.contains("rand::"));
    }

    #[test]
    fn test_generate_normal() {
        let dist = ProbDistribution::Normal { mean: 5.0, std: 2.0 };
        let code = generate_probabilistic_code(&dist, &[5.0, 2.0], "noise");
        assert!(code.contains("μ = 5.0000"));
        assert!(code.contains("σ = 2.0000"));
        assert!(code.contains("Normal::new"));
    }

    #[test]
    fn test_generate_poisson() {
        let dist = ProbDistribution::Poisson { lambda: 4.5 };
        let code = generate_probabilistic_code(&dist, &[4.5], "count_events");
        assert!(code.contains("λ = 4.5000"));
        assert!(code.contains("fn count_events()"));
    }

    #[test]
    fn test_generate_categorical() {
        let dist = ProbDistribution::Categorical(vec![0.2, 0.3, 0.5]);
        let code = generate_probabilistic_code(&dist, &[0.2, 0.3, 0.5], "roll_die");
        assert!(code.contains("0.2000, 0.3000, 0.5000"));
        assert!(code.contains("fn roll_die()"));
    }
}
